### ISSUE TITLE
What filter do you use?

### ISSUE THREAD

**Issue by lancelot-moon** [ookangzheng/blahdns#1]
Hi,

Is it possible that you give the filter lists which you use for BlahDNS?
Only EasyPrivacy + EasyList?
Why do you not set a DNS server in Taiwan?

Thanks.

**Comment by Atavic** [comment]
See: https://github.com/ookangzheng/blahdns/tree/master/hosts

**Comment by lancelot-moon** [comment]
Wow, you also know I post an issue here.
Thanks for the reply!

**Comment by Atavic** [comment]
You can do it, click on *Issues* on the top bar and put *Atavic* instead of your nick.

**Comment by ookangzheng** [comment]
@lancelot-moon Hi there,
Sorry for the late reply. Because rent a VPS and bandwidth in Taiwan are very expensive.
Recently, I added OpenNIC too. so you can visit http://nx.bit/ some cool domain

**Comment by lancelot-moon** [comment]
I don’t understand why you talk about OpenNIC.
BlahDNS should be different with OpenNIC, right?
Well, I’m just interested in which filters you use and if they are update to date.

You can use 1hosts.cf as your filter, too.

**Comment by ookangzheng** [comment]
@lancelot-moon 
I have some friend they wanna visit OpenNIC based domain, so It should work well both (ICANN and OpenNIC)
I will check later, thanks for your suggestion.
