### ISSUE TITLE
AMP

### ISSUE THREAD

**Issue by p1r473** [ookangzheng/blahdns#100]
Hello,
Are you blocking AMP on purpose?
One domain being blocked is
cdn-content.ampproject.org

Which is the AMP CDN

**Comment by ookangzheng** [comment]
I do not block this on purpose though. 
Let me check it out.

**Comment by ookangzheng** [comment]
I seems like both server is not block `cdn-content.ampproject.org`. 
Pls confirm that you are using Blahdns service. Thanks

**Comment by p1r473** [comment]
https://github.com/ookangzheng/blahdns/blob/master/hosts/blacklist.txt#L214

**Comment by ookangzheng** [comment]
Pls ignore the blacklist.txt from now.
Once I've free time, I will remove it or PR is welcome. 👍
