### ISSUE TITLE
Blahdns blocks Opera Mini

### ISSUE THREAD

**Issue by KelvinCrag** [ookangzheng/blahdns#102]
When I want to surf the net with [Opera Mini](https://play.google.com/store/apps/details?id=com.opera.mini.native)  I'm told '**Unable to connect. Please review your network settings.**' But works when I turn off my private dns or change my private dns hostname to something else.
Kindly resolve this issue mate. Thanks.

**Comment by ookangzheng** [comment]
@@||opera-mini.net^, opera.software, op-cdn.net

Fixed
