### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by Jostian** [ookangzheng/blahdns#106]
Is the server down? i have no internet access on WiFi or data? If i disable dns all works fine again. J

**Comment by chris-kwl** [comment]
Have the same problem with dot, tested (dot-de and dot-fi). Domain is reachable and Server status up (https://stats.blahdns.com/781148193).
I use the Android 10 "Private DNS" feature.
Sadly not the first time there are connection problems with configured dot. Don't know any way to log here.

**Comment by Jostian** [comment]
For me dot-de is not working, will try dot-fi, thanks

**Comment by ookangzheng** [comment]
Sorry guys, 
I switched local DNS port to other number and I forgot to change Haproxy config as well. 
Now DoT will work as expected.

Thanks
