### ISSUE TITLE
dot-de.blahdns.com connection error

### ISSUE THREAD

**Issue by GithubOwly** [ookangzheng/blahdns#107]
Hi,

Do you have a Problem with your dot-de.blahdns.com server?
The doh server is not working also.

Thanks for your good work.
regards!

**Comment by black-ish** [comment]
Seems to be having an issue, dnscrypt-de server is also erroring.

**Comment by ookangzheng** [comment]
I think everything would be fine now. My server harddrive full 😅

**Comment by black-ish** [comment]
Can confirm that the dnscrypt server works again.

**Comment by ookangzheng** [comment]
Will close this issue from now. 
Thanks for your feedback.
