### ISSUE TITLE
BlahDNS: Cloudflare and QUAD9.

### ISSUE THREAD

**Issue by szemley** [ookangzheng/blahdns#113]
Hello **ookangzheng**.

I've noticed recently that Cloudflare and QUAD9 informations are "_removed_" (generally, crossed out). It was bound to happen, anyway? Do You have any problems?

By the way: I did a quick test on `grc.com` and now, `Queries Received` are much, much smaller than - let say - two months ago (maybe longer). Now, it's e.g. `204` etc. and the final result is about `1000-2500`. In the past, it was `20.000-30.000` Queries! I've never had seen something like that! Really, it was amazing.

Also, now there is less red dots, but of course, result is still very good! In the past, when there was `20.000-30.000` Queries, red dots were everywhere. It was amazing.

Anyway, maybe I'll start using BlahDNS again **:- )** Sorry for reminiscences. Keep up good work! 

Best regards.

**Comment by ookangzheng** [comment]
Will close this issue, if you still having issue, pls consider file an issue. 

Thanks
