### ISSUE TITLE
Downloading twitter mp4.

### ISSUE THREAD

**Issue by yutayu** [ookangzheng/blahdns#118]
**Checklist**

- [x ] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [ x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [ x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)
- [ x ] My issue is about the blahdns, and not DNS itself

**Describe the issue**
A clear and concise description of what the issue is.

When I use blahdns( I use jp.) , it stops downloading twitter mp4.

**To Reproduce**

1. ...

**Expected behavior**
I want to download mp4 completely.

**Logs**
If applicable, add logs or screenshots to help explain your problem.

If you can reproduce the issue, please describe it below.

**Server if applicable):**

- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. Vultr, AWS, OpenWRT, RaspberryPI]
raspberrypi
**Client (if applicable):**
same
- Device: [e.g. iPhone, Android, Linux, Windows]
- OS: [e.g. iOS13, Android 10, Debian 10, Windows 10]
- Client: [e.g. Nebulo, Unbound, Bind9, Dnscrypt-v2, Intra]
dnscrypt-proxy
- Protocol: [e.g. DoH, DoT, Dnscrypt]
doh dnscrypt
**Additional context**

**Comment by ookangzheng** [comment]
What is the URL ?

**Comment by yutayu** [comment]
please find long time videos lol

**Comment by ookangzheng** [comment]
![image](https://user-images.githubusercontent.com/6301735/90306969-ef8bc800-df04-11ea-9793-7913cb842be4.png)
I was able to download..

**Comment by yutayu** [comment]
![Screenshot from 2020-08-15 19-14-08](https://user-images.githubusercontent.com/44407536/90310336-9f742c00-df2b-11ea-84b8-d3e4725df96c.png)

This is mine.

**Comment by ookangzheng** [comment]
So can you this on your `terminal` with following command, and let me know what is the result
Command: `dig video.twimg.com`

Thanks

**Comment by yutayu** [comment]
root@raspberrypi:/home/pi# drill video.twimg.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 10205
;; flags: qr rd ra ; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; video.twimg.com.	IN	A

;; ANSWER SECTION:
video.twimg.com.	21520	IN	CNAME	cs296.wpc.edgecastcdn.net.
cs296.wpc.edgecastcdn.net.	21520	IN	CNAME	cs2-wpc.apr-8315.edgecastdns.net.
cs2-wpc.apr-8315.edgecastdns.net.	21520	IN	CNAME	cs2-wpc-as.8315.ecdns.net.
cs2-wpc-as.8315.ecdns.net.	21520	IN	CNAME	cs531.wpc.edgecastcdn.net.
cs531.wpc.edgecastcdn.net.	21520	IN	A	117.18.232.102

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.1
;; WHEN: Sun Aug 16 20:48:11 2020
;; MSG SIZE  rcvd: 212

**Comment by yutayu** [comment]
![Screenshot from 2020-08-16 20-52-44](https://user-images.githubusercontent.com/44407536/90333638-783c5e00-e002-11ea-9ced-f0c7845e874b.png)

I can download that file just now with blahdns , cloudflare.

**Comment by yutayu** [comment]
Please pend this issue.

**Comment by yutayu** [comment]
I can download twitter mp4 without problems, after timestamp got on.
net.ipv4.tcp_timestamps = 0
to
net.ipv4.tcp_timestamps = 1

**Comment by yutayu** [comment]
Till now , no error occurs.
so my modify was failed.
Very sorry, this is not on blahdns's business. 
Thanks :)
