### ISSUE TITLE
🐛 Whitelist *.ad.jp 

### ISSUE THREAD

**Issue by yutayu** [ookangzheng/blahdns#121]
**Checklist**

- [x ] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x ] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [ x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
A clear and concise description of what the issue is.
blocking *.ad.jp
**To Reproduce**
try to watch
https://www.mfeed.ad.jp/ntp/detail.html

1. ...
2. ...

**Expected behavior**

**Logs (optional)**
If applicable, add logs or screenshots to help explain your problem.

If you can reproduce the issue, please describe it below.

**Server if applicable):**

- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. Vultr, AWS, OpenWRT, RaspberryPI]

**Client (if applicable):**

- Device: [e.g. iPhone, Android, Linux, Windows]
linux
- OS: [e.g. iOS13, Android 10, Debian 10, Windows 10]
raspbian
- Client: [e.g. Nebulo, Unbound, Bind9, Dnscrypt-v2, Intra]
Unboud
- Protocol: [e.g. DoH, DoT, Dnscrypt]
DoT
**Additional context**
Thanks :)

**Comment by yutayu** [comment]
.ad.jp
means an administrator.
so , usually white site.

**Comment by ookangzheng** [comment]
Fixed

**Comment by yutayu** [comment]
Thanks!
