### ISSUE TITLE
🐛 Not resolving NTP servers

### ISSUE THREAD

**Issue by skibbipl** [ookangzheng/blahdns#122]
When I use Gernamy DoH server my DNS cannot resolve following addresses:
```
0.debian.pool.ntp.org
1.debian.pool.ntp.org
2.debian.pool.ntp.org
3.debian.pool.ntp.org
```

**Comment by ookangzheng** [comment]
It is necessary to use those addresses to sync your time? or you can try to use another alternative.
Because those addresses used as attack targets. 
https://www.ntppool.org/en/

**Comment by skibbipl** [comment]
Well I expect from DNS server to return all existing addresses. I can change NTP servers but I don't trust this DNS anymore 👎

**Comment by ookangzheng** [comment]
Cuz sometimes I encounter some IPs request a lot of PTR or NTP request.

It will make the CPU 100%, which will affect other user's resolve DNS. Therefore, I kinda do a balance on this situation.
My machine specification currently doesn't have LoadBalance and auto-fail recovery. 
Just a 10USD budget VPS

**Comment by skibbipl** [comment]
So perhaps you could share your setup so people could set their own "blahdns" nodes and make this more distributed? I can set my own VPS for that.

**Comment by ookangzheng** [comment]
This problem has been solved on Germany server

**Comment by ookangzheng** [comment]
Will close from now. If you need further assistance, pls don't hesitate to let me know. 
Thanks
