### ISSUE TITLE
🐛 SG server TLS not working on Stubby (OpenWRT)

### ISSUE THREAD

**Issue by klennix** [ookangzheng/blahdns#123]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
SG server TLS not working on Stubby (OpenWRT/GL.iNET)

1. Internet not connected

My setting:
# # BlahDNS-sg
- address_data: 139.180.141.57
  tls_auth_name: "dot-sg.blahdns.com"
  tls_port: 853

- Protocol: DoT

**Additional context**
My location is Indonesia, DoH and DNSCrypt is working great.

**Comment by ookangzheng** [comment]
Can you share yours stubby.yml configuration here?

**Comment by cebolang** [comment]
#NOTE: See '/etc/stubby/stubby.yml.default' for original config file and descriptions

resolution_type: GETDNS_RESOLUTION_STUB

dns_transport_list:
   - GETDNS_TRANSPORT_TLS
#  - GETDNS_TRANSPORT_UDP
#  - GETDNS_TRANSPORT_TCP

#tls_authentication: GETDNS_AUTHENTICATION_NONE

tls_authentication: GETDNS_AUTHENTICATION_REQUIRED

dnssec_return_status: GETDNS_EXTENSION_TRUE

tls_query_padding_blocksize: 128

edns_client_subnet_private : 1

round_robin_upstreams: 0

idle_timeout: 10000

tls_connection_retries: 3

tls_backoff_time: 300

listen_addresses:
  - 127.0.0.1@53535
  -  0::1@53535

upstream_recursive_servers:

## dot.tiar.app
#- address_data: 174.138.29.175
#  tls_auth_name: "dot.tiar.app"
#  tls_port: 853
#- address_data: 2400:6180:0:d0::5f73:4001
#  tls_auth_name: "dot.tiar.app"
#  tls_port: 853

## Adguard Family Protection
#  - address_data: 176.103.130.132
#    tls_auth_name: "dns-family.adguard.com"
#  - address_data: 176.103.130.134
#    tls_auth_name: "dns-family.adguard.com"

## BlahDNS-sg
- address_data: 139.180.141.57
  tls_auth_name: "dot-sg.blahdns.com"
  tls_port: 853

## BlahDNS-jp
#- address_data: 45.32.55.94
#  tls_auth_name: "dot-jp.blahdns.com"
#  tls_port: 853

## Quad 9
#  - address_data: 9.9.9.10
#    tls_auth_name: "dns.quad9.net"
#  - address_data: 2620:fe::10
#    tls_auth_name: "dns.quad9.net"

**Comment by cebolang** [comment]
#NOTE: See '/etc/stubby/stubby.yml.default' for original config file and descriptions

resolution_type: GETDNS_RESOLUTION_STUB

dns_transport_list:
   - GETDNS_TRANSPORT_TLS
#  - GETDNS_TRANSPORT_UDP
#  - GETDNS_TRANSPORT_TCP

#tls_authentication: GETDNS_AUTHENTICATION_NONE

tls_authentication: GETDNS_AUTHENTICATION_REQUIRED

dnssec_return_status: GETDNS_EXTENSION_TRUE

tls_query_padding_blocksize: 128

edns_client_subnet_private : 1

round_robin_upstreams: 0

idle_timeout: 10000

tls_connection_retries: 3

tls_backoff_time: 300

listen_addresses:
  - 127.0.0.1@53535
  -  0::1@53535

upstream_recursive_servers:

## dot.tiar.app
#- address_data: 174.138.29.175
#  tls_auth_name: "dot.tiar.app"
#  tls_port: 853
#- address_data: 2400:6180:0:d0::5f73:4001
#  tls_auth_name: "dot.tiar.app"
#  tls_port: 853

## Adguard Family Protection
#  - address_data: 176.103.130.132
#    tls_auth_name: "dns-family.adguard.com"
#  - address_data: 176.103.130.134
#    tls_auth_name: "dns-family.adguard.com"

## BlahDNS-sg
- address_data: 139.180.141.57
  tls_auth_name: "dot-sg.blahdns.com"
  tls_port: 853

## BlahDNS-jp
#- address_data: 45.32.55.94
#  tls_auth_name: "dot-jp.blahdns.com"
#  tls_port: 853

## Quad 9
#  - address_data: 9.9.9.10
#    tls_auth_name: "dns.quad9.net"
#  - address_data: 2620:fe::10
#    tls_auth_name: "dns.quad9.net"

**Comment by ookangzheng** [comment]
I modified your configuration and tested on my Mac OSX with v1.6.0 stubby
[stubby.txt](https://github.com/ookangzheng/blahdns/files/5192231/stubby.txt)

Note: Remember to change `stubby.txt` to `stubby.yml`

**Comment by ookangzheng** [comment]
Feedback?
@cebolang

**Comment by cebolang** [comment]
Still can't work.

**Comment by ookangzheng** [comment]
Sorry, I can't help with this.
Maybe you may need someone who have experience in OpenWRT.
