### ISSUE TITLE
280blocker is blocklist for japanese site.

### ISSUE THREAD

**Issue by yutayu** [ookangzheng/blahdns#124]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

https://280blocker.net/
https://280blocker.net/download/
https://280blocker.net/files/280blocker_domain.zip

How about using this list for ad blocking.

**Comment by ookangzheng** [comment]
Added this `https://280blocker.net/files/280blocker_domain.txt` to BlahDNS Japan server, 
pls give it a try~

**Comment by yutayu** [comment]
pi@raspberrypi:/etc/dnscrypt-proxy $ drill 2mdn.info
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 7097
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; 2mdn.info.	IN	A

;; ANSWER SECTION:
2mdn.info.	21599	IN	A	0.0.0.0

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 19 msec
;; SERVER: 127.0.0.1
;; WHEN: Sun Sep 13 21:33:18 2020
;; MSG SIZE  rcvd: 52
pi@raspberrypi:/etc/dnscrypt-proxy $ 


It seeems to work. :)
Thanks.

**Comment by yutayu** [comment]
please add # lines below of that lists.

**Comment by yutayu** [comment]
sorry , my test was fault.
you already added those.

**Comment by yutayu** [comment]
pi@raspberrypi:~ $ drill app.adjust.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 18335
;; flags: qr rd ra ; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; app.adjust.com.	IN	A

;; ANSWER SECTION:
app.adjust.com.	21599	IN	A	185.151.204.6
app.adjust.com.	21599	IN	A	185.151.204.7
app.adjust.com.	21599	IN	A	185.151.204.8
app.adjust.com.	21599	IN	A	185.151.204.9

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 122 msec
;; EDNS: version 0; flags: ; udp: 4096
;; SERVER: 127.0.0.1
;; WHEN: Tue Sep 15 17:57:29 2020
;; MSG SIZE  rcvd: 163

excuse me , still I can get this ip.

**Comment by ookangzheng** [comment]
If block `app.adjust.com`, will brake the Spotify app

**Comment by yutayu** [comment]
ah you know it . no problem . thanks.
