### ISSUE TITLE
Weird site resolving problems across DOH servers🐛 

### ISSUE THREAD

**Issue by obeho** [ookangzheng/blahdns#126]
**Checklist**

- [Y] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [Y] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [Y] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
https://privacytools.io website (PTIO) not getting resolved

**To Reproduce**

1. Use https://doh-fi.blahdns.com/dns-query server as DOH with no fallback on Firefox, Windows 10 or on Android 10 with the same DNS set with no fallback, and try to open the PTIO site, error will be displayed (ERR_NAME_NOT_RESOLVED)

2. Use https://doh-de.blahdns.com/dns-query server on same environments, everything works fine.

**Additional context**
I recently shifted from the Germany server to Finland server, but previously when I was using the Germany server for more than a year, sometimes the PTIO site wasn't getting resolved, I thought it was a down, but now, I'm sure this is some sort of bug/issue.

And all other sites were working fine on both the servers, till now. (As far as I remember). Location : India

**Comment by ookangzheng** [comment]
I encountered this problem too, so far I will whitelist privacytools.io

**Comment by obeho** [comment]
Thank you. What I fear is that this problem might not be confined to this one domain, so far I haven't found any other site with similar behaviour, but this might be due to my limited browsing activity. 

Anyways, on the off-topic, I was using Germany DOH since it was slightly closer to me than the Finland one, and didnt want to use any Asian ones. I shifted to the Finland server few days back, and boom, the latency dropped by a substantial amount, there was almost 0 buffering time. I'm glad I did this transition.

**Comment by ookangzheng** [comment]
You can try https://doh2.blahdns.com/dns-query or https://doh2.blahdns.com/uncensor (No Adblock, etc..)
This has CDN in front of it, and the DNS query will resolve on the Finland server.

**Comment by obeho** [comment]
Thanks 👍  

Ok, I don't know why, but https://doh2.blahdns.com/dns-query, using this server made latency go higher, like worse than the normal Germany DOH. I'm back to using the lovely https://doh-fi.blahdns.com/dns-query.

Which CDN do you use? If you dont mind my asking.

On the off-topic 

> Need some refactor and auto CI/CD

https://about.gitlab.com/blog/2019/10/07/auto-devops-explained/

Please dont laugh at me if I'm late or just wrong. I just wanted to help.

**Comment by ookangzheng** [comment]
I use BunnyCDN.  but connection latency and pops will depends on your location and ISP. 

I will close this issue for now. If you still having issue with BlahDNS, Pls issue a new ticket. 

Thanks.
