### ISSUE TITLE
Genuine site whitelist

### ISSUE THREAD

**Issue by obeho** [ookangzheng/blahdns#128]
**Checklist**

- [Y] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [Y] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [Y] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
https://click.revue.email/ss/c/ is an email newsletter redirecter for loading the requisite website.

**Expected behavior**
If resolved properly, the following error message should be displayed.

> **Wrong Link**
> 
> You have clicked on an invalid link. Please make sure that you have typed the link correctly. If are copying this link from a mail reader please ensure that you have copied all the lines in the link.

**Additional context**
This genuine site whitelisting request seems to be a recurring issue here on github. Could you provide other means/platform of reporting on this issue to reduce cluttering?

**Comment by ookangzheng** [comment]
Whitelisted.

_Found on hblock https://hblock.molinero.dev/hosts_adblock.txt_

**Comment by obeho** [comment]
Thank you, I also wanted to request the whitelisting of plausible.io, its on hblock.

**Comment by ookangzheng** [comment]
Done ~ `plausible.io`

**Comment by obeho** [comment]
Thanks
