### ISSUE TITLE
Adguard landing page displayed

### ISSUE THREAD

**Issue by obeho** [ookangzheng/blahdns#129]
**Checklist**

- [Y] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [Y] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [Y] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Opening the site https://yerl.org/public on Finland DOH shows the below Adguard's landing page,

![issue](https://user-images.githubusercontent.com/71698631/94609842-fdcb5300-02bc-11eb-9049-8051c98768b0.JPG)

I've tried this on my PC and my mobile on different browsers too, but was only using Blah DNS on both. And when I use some other DNS resolver, the landing page is no longer shown, and the site works just fine.

**Additional context**

Shouldn't the site simply not be resolved here? How and why is Adguard inserting itself simply by using Blah DNS?

I should mention that this error did pop-up while visiting the site,

![issue2](https://user-images.githubusercontent.com/71698631/94611341-3d933a00-02bf-11eb-8db2-82f1d8b4a3c5.jpg)

**Comment by ookangzheng** [comment]
Interesting found. 

I replaced return IP to 0.0.0.0 instead of Adguard IP.
DNS resolution will send a query to AdGuard IP to check if its a bad site. If true, then return false.
Also whitelisted this domain.

**Comment by obeho** [comment]
Thank you.

This issue, it seems is not restricted to this one site though. The popular note-taking website evernote.com also, is "taken over" 😄  by the adguard landing page, though this effect is no longer seen with BlahDNS because of the change in return IP. Also, the https://yerl.org/public site's certificate is updated now.

I wish to ask, why was the return IP set as adguard IP in case of bad site? Instead of just not resolving? Was this something that was done on purpose or overlooked?

Are there any more such cases of return IP's being some third-party domains?

**Comment by ookangzheng** [comment]
From my point of view, BlahDNS is an attempt to block Phishing or Malware site. 
Since all blacklist relies on the public blacklist, won't be an ability to block ASAP. 
Therefore, I will try to look up to AdGuard `176.103.130.130`. 

Example: `dig yerl.org @176.103.130.130`

If returns answer A record match `176.103.130.133`, then return it to user. 
This action will ignore the upper DNS resolution result.

**Comment by obeho** [comment]
I admire the standpoint of blocking sites that are phishing or malware. But I'm concerned about the need of displaying an Adguard landing page, instead of just not-resolving, like all other sites on the blacklists. On the other hand, if you insist upon the need for educating users that a particular site is a phishing/malware site, that is also good, but in that case too, the Adguard page can be skipped, IMO. Instead you could just your own landing page with the same info.

**Comment by ookangzheng** [comment]
So far, I will just not to resolve those "malware/phishing" sites and return `0.0.0.0` instead of showing an annoying page.

**Comment by ookangzheng** [comment]
Will close this issue. Please consider open a new issue for further discussion.
