### ISSUE TITLE
Coinbase blocked domain..

### ISSUE THREAD

**Issue by mkaand** [ookangzheng/blahdns#13]
Hello,

I use DNS Cloak on my iPhone X. BlahDNS and DNS Cloak are very nice projects. Thank you very much for developers. I used to use BlahDNS but I found out It blocks coinbase.com website. I have their ios app and it doesn't work with BlahDNS. How to I can exclude coinbase.com? It is safe website actually. I want to reuse BlahDNS but first I should able to access coinbase website.

**Comment by ookangzheng** [comment]
Can you send me some coinbase.com URL on Iphone? 
I don't have iphone

**Comment by mkaand** [comment]
According to DNS Cloak logs I see following hostnames when I try to open coinbase app:

am.coinbase.com
api.coinbase.com
www.coinbase.com
coinbase.com

**Comment by ookangzheng** [comment]
Done, include the main site, assets, login and websocket

**Comment by mkaand** [comment]
Thank you :)

**Comment by mkaand** [comment]
Hi again,

I use Buffer app on my mobile to share some updates to my social networks. It seems api.bufferapp.com blocked too. Could you unblock it? It is safe website I confirm that. Actually they provide very nice free service for social media users. Thanks.

**Comment by ookangzheng** [comment]
Done

**Comment by mkaand** [comment]
Thank you :)

**Comment by ookangzheng** [comment]
Done
