### ISSUE TITLE
 cn-geo1.uber.com🐛 

### ISSUE THREAD

**Issue by p1r473** [ookangzheng/blahdns#131]
**Checklist**

- [X ] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [X ] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [X ] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
cn-geo1.uber.com required for Uber services

**To Reproduce**

1.  Can not use Uber Eats app

**Expected behavior**
Uber Eats should work 

If you can reproduce the issue, please describe it below.

**Server if applicable):**

- OS: Debian
- Hosting provider (if applicable): Asus TinkerBoard S

**Client (if applicable):**

- Device: Android,
- OS: Android 10
- Client: PiHole
- Protocol: DNS

**Additional context**
This domain is required for Uber services (Uber eats, etc)
It is a geolocation service, but is not meant for spying.
I will leave it to you to consider whether you whitelist it (I whitelisted it on my end)

**Comment by ookangzheng** [comment]
Fixed

**Comment by p1r473** [comment]
Thanks!
