### ISSUE TITLE
is Disqus.com blocked? need whitelist

### ISSUE THREAD

**Issue by GrennKren** [ookangzheng/blahdns#136]
Just realize that I cant connect to disqus.com for reason "refused to connect" in chrome. Also just like usual, has been checked through blahdns.com

**Comment by obeho** [comment]
Yes it is. As usual by ADgk. @ookangzheng perhaps its time to rethink this blocklist.

**Comment by ookangzheng** [comment]
Already removed `https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt`
Thanks

**Comment by GrennKren** [comment]
Thanks!
