### ISSUE TITLE
Limitation query number per time.

### ISSUE THREAD

**Issue by yutayu** [ookangzheng/blahdns#139]
**Question description**

subject.

**Comment by ookangzheng** [comment]
?? What do you mean

**Comment by yutayu** [comment]
Reguration of this server . queue number limitation per second.  
some dns server refuse query like DDoS.

**Comment by ookangzheng** [comment]
Ya, I will try it out.

**Comment by yutayu** [comment]
Sorry , I wanted to know server setting.
If i got server setting , I will modify my dns server setting.
for example , I reduce max-forward-queries of dnsmasq.

**Comment by ookangzheng** [comment]
Which server are you using?
I still investigate on rate limit TCP and UDP

**Comment by yutayu** [comment]
Japan DNSCrypt v1 or v2.
maybe I only use UDP.

**Comment by ookangzheng** [comment]
DNSCrpyt only has v2.
It has tcp and udp.

**Comment by yutayu** [comment]
Nov 03 13:29:13 raspberrypi dnscrypt-proxy[580]: [2020-11-03 13:29:13] [NOTICE] [dnscrypt-jp-blahdns-ipv4] OK (crypto v1) - rtt: 15ms

Isn't this v1?

**Comment by ookangzheng** [comment]
Nope, cuz I'm using dnsdist to serve Dnscrypt protocol.
https://dnsdist.org/guides/dnscrypt.html

**Comment by yutayu** [comment]
ok

**Comment by ookangzheng** [comment]
I try on Japan Server with the following setting

Incoming 60 seconds > 20 connections (parallel) , will drop those packet.

**Comment by yutayu** [comment]
ok thanks. I set according to that.
maybe, max-forward-queries = 2

**Comment by yutayu** [comment]
It seems smooth.
