### ISSUE TITLE
🐛 Youtube History not Working on doh-sg-blahdns in DNSCloak 

### ISSUE THREAD

**Issue by stonesx** [ookangzheng/blahdns#140]
**Checklist**

- [ ] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [ ] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [ ] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Youtube iOS app history is not updated upon watching new clips. This is happening on using doh-sg-blahdns in  DNSCloak iOS app.

**To Reproduce**

1. Turn on doh-sg-blahdns in DNSCloak iOS app
2. Watch clips on Youtube app.
3. Youtube history is not updated with the watched clips.

**Expected behavior**
Youtube history should be updated with the watched clips.

**Logs (optional)**
None.

If you can reproduce the issue, please describe it below.

**Server if applicable):**

- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. Vultr, AWS, OpenWRT, RaspberryPI]

**Client (if applicable):**

- Device: iPhone
- OS: iOS 14.1
- Client: DNSCloak
- Protocol: DoH

**Additional context**
None.

**Comment by ookangzheng** [comment]
Added to allowlist.
_Found Stevenblack blocklist._

**Comment by obeho** [comment]
Is it this domain `s.youtube.com`? @ookangzheng

**Comment by stonesx** [comment]
Cannot tell. It is youtube iOS app. But I read somewhere that it is this domain you stated below and one more domain. I cannot find that article anymore. 

Chris Chan

**Comment by stonesx** [comment]
The YouTube iOS app history is working now. 

Chris Chan

**Comment by ookangzheng** [comment]
If you block `s.youtube.com`, watch history won't be saved in the web browser.
Ios or Android youtube app won't affect.

**Comment by stonesx** [comment]
No I did not block the domain. I used blah doh via DNSCloak and the history in the YouTube app did not work for days until this morning. Now it is working. I did not change anything. 

Chris Chan

**Comment by obeho** [comment]
> Android youtube app won't affect.

It effects on Android @ookangzheng . I use NextDNS on one of my devices, and `s.youtube.com` was blocked, and the past 6 days watch history was not saved. Today, I whitelisted the domain, and I can see the history is saved correctly.

**Comment by ookangzheng** [comment]
Ya, I noticed this issue.
Pls try again, I whitelisted `s.youtube.com`

**Comment by obeho** [comment]
> I whitelisted `s.youtube.com`

Yes

> I use NextDNS on one of my devices

I was talking about this

**Comment by ookangzheng** [comment]
Will close this issue for now.
