### ISSUE TITLE
Any privacy enhancement planned?🤗 

### ISSUE THREAD

**Issue by Sami32** [ookangzheng/blahdns#142]
**Question description**

https://dnsprivacy.org/jenkins/job/dnsprivacy-monitoring/

**Comment by ookangzheng** [comment]
What kind of "privacy enhancement"? 
As "dnsprivacy.org" state, BlahDNS are fit in most of their criteria.

**Comment by obeho** [comment]
I think there are two. Strict SPKI can be done, increasing security/privacy. And Out Of Order Responses is a very good performance enhancement.

**Comment by ookangzheng** [comment]
Strict SPKI can be done by using wildcard SSL cert or manually handle Let's encrypt private key rotate. 
OOR limitation is due to the HAProxy issue as Loadbalancer.

**Comment by Sami32** [comment]
As @obeho said.
More the coming E.C.H.O. support:
https://datatracker.ietf.org/doc/draft-ietf-tls-esni/

I'm not sure to have understood the answer...do that mean no?
In such case then feel free to close this "issue".

Best regards,

**Comment by ookangzheng** [comment]
Hmm, what I know about current implementation are
1. No EDNS client sent to auth server
2. No log is kept
3. Qname minimization enabled
4. Adblock
5. Cname cloaking enabled
6. HTTPS/ TLS1.3
7. Systemd journal log or others operating system logs are stored under `var/log` will be wipe on 12A.M.
...
what else can be improve? Cuz I not a pro at this, but will keep learning and try to progressively improve.

**Comment by Sami32** [comment]
I appreciate your work and used your DNS server the last year ;)

Encrypted Server Name Indication is a must to have imho but the official IETF standard should be finalized in march 2021 only.

I'm mostly using DNS privacy servers for my Android smartphones.

Strict SPKI support would be nice.

In any case i was just wondering about your plan.

Best regards,

**Comment by ookangzheng** [comment]
Currently, there is no plan.
But during my free time, will research SPKI and DoQ

**Comment by Sami32** [comment]
Thank for your honest answer +1

If you mean:
https://datatracker.ietf.org/doc/draft-ietf-dprive-dnsoquic/
https://tools.ietf.org/html/draft-ietf-quic-transport-32
https://tools.ietf.org/html/draft-ietf-quic-tls-32

It is 2/3 years away from finalization imho...

**Comment by ookangzheng** [comment]
I gonna close this issue. Pls feel free to reopen if you have any question. 
Thanks

**Comment by obeho** [comment]
@ookangzheng 
1. Do you have TLSA records for your DNS endpoints?
2. You might want to look at The edns-tcp-keepalive EDNS0, as outlined by RFC [7828](https://tools.ietf.org/html/rfc7828), and its implementation in BlahDNS.
3. In the above [comment](https://github.com/ookangzheng/blahdns/issues/142#issuecomment-722263668) you mentioned that TLS1.3 is supported. But are TLS 1.0 and 1.1 deprecated? If not, support for these two versions should be dropped.
4. And, I assume [this](https://tools.ietf.org/html/rfc8806) is already implemented?
5. Also, please drop the DNS ANY meta-query type. [(link)](https://blog.cloudflare.com/deprecating-dns-any-meta-query-type/)
