### ISSUE TITLE
Incorrect signature for provider name: [2.dnscrypt-cert.blahdns.com.]

### ISSUE THREAD

**Issue by Bushwickz** [ookangzheng/blahdns#143]
<img width="990" alt="2 dnscrypt-cert blahdns com" src="https://user-images.githubusercontent.com/65140377/98544172-9c09eb80-2261-11eb-9c5a-196546a05efb.png">

**Comment by ookangzheng** [comment]
Fixed, pls update the latest dns stamp
`sdns://AQMAAAAAAAAAG1syYTAxOjRmODpjMTc6ZWM2Nzo6MV06ODQ0MyBThOgUQxQpPlbdGxQKHvFyrUe9uheZyJVylJU9A061xxsyLmRuc2NyeXB0LWNlcnQuYmxhaGRucy5jb20`

**Comment by ookangzheng** [comment]
problem solved?

**Comment by Bushwickz** [comment]
> problem solved?

Solved. Thanks!
