### ISSUE TITLE
Please add Xbox Whitelist to your DNS filter🚀 

### ISSUE THREAD

**Issue by ysguy** [ookangzheng/blahdns#144]
**Is your feature request related to a problem?**
Yes, cannot sign into xbox live on an xbox using your DNS. Overriding with 8.8.8.8 fixes the issue.

**Describe the solution you'd like**
Add the following whitelisted URL's

clientconfig.passport.net 
v10.events.data.microsoft.com
v20.events.data.microsoft.com
xbox.ipv6.microsoft.com 
device.auth.xboxlive.com 
www.msftncsi.com 
title.mgt.xboxlive.com 
xsts.auth.xboxlive.com 
title.auth.xboxlive.com 
ctldl.windowsupdate.com 
attestation.xboxlive.com 
cdn-resources.prfct.cc
prfct.cc
xboxexperiencesprod.experimentation.xboxlive.com 
xflight.xboxlive.com 
cert.mgt.xboxlive.com 
xkms.xboxlive.com 
def-vef.xboxlive.com 
notify.xboxlive.com 
help.ui.xboxlive.com 
licensing.xboxlive.com 
eds.xboxlive.com 
www.xboxlive.com 
v10.vortex-win.data.microsoft.com 
settings-win.data.microsoft.com
cdn-assets.prfct.cc
mobile.pipe.aria.microsoft.com

**Describe alternatives you've considered**
manually overriding my xbox DNS

**Additional context**
Unnecessary.

**Comment by ookangzheng** [comment]
Actually, *.xboxlive.com, *.microsoft.com already whitelist on BlahDNS server. Pls try again.

**Comment by ookangzheng** [comment]
Will close this issue. If you have any feedback please reopen this issue.

Thanks
