### ISSUE TITLE
www.google.com is blocked but not google.com

### ISSUE THREAD

**Issue by GrennKren** [ookangzheng/blahdns#146]
need whitelist for `www.google.com` 
now im wondering which filter caused this

**Comment by Polluktus** [comment]
Same problem, Firefox 83 DoH from german server. www.google.com is blocked, when every other (.fr, .pl, .ru, .sh) are available.

**Comment by ookangzheng** [comment]
Fixed

Found from the source: `https://abp.oisd.nl`

**Comment by GrennKren** [comment]
thanks ookangzheng
