### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by ryder203** [ookangzheng/blahdns#147]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
blahDNS blocks playback of some youtube videos. Tested using various browsers with and without plugins.
I took the youtube URL, copy & paste in all browsers - chromium with add-ons, without add-ons, firefox no add-ons installed at all, new MS edge... Video not loading. I go to my router settings, remove blahDNS, wait for 2 minutes and reload page, video plays in all browsers.

**To Reproduce**
Steps to reproduce the behavior: Add blahDNS as DNS servers in Fritzbox as DoT. Play many youtube videos, some just show black screen with loading animation.

**Expected behavior**
All videos on youtube just play... =P

**Logs (optional)**
nope.

**Server if applicable):**

nope.

**Client (if applicable):**

- OS: Windows 10
- Hosting provider (if applicable): German Telekom
- Router Fritzbox 7590 (German)

![photo_2020-11-29_22-08-14](https://user-images.githubusercontent.com/21237183/101215696-8e882b80-367e-11eb-9b0c-98a6c6034d60.jpg)

**DoT/Servers:**
dot-de.blahdns.com
dot-jp.blahdns.com
dot-fi.blahdns.com
dot-sg.blahdns.com

**Additional context**
blahDNS not usable that way. Will wait for fix.

_I was able to reproduce the error using my Android device: newpipe and youtube vanced did not play videos either._

**Comment by ookangzheng** [comment]
Pls try again, maybe this cuz problem
https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt
