### ISSUE TITLE
Cant play QuizUp

### ISSUE THREAD

**Issue by sivajipro** [ookangzheng/blahdns#15]
https://play.google.com/store/apps/details?id=com.quizup.core

Can play single player mode.
But cant play random player mode.

**Comment by ookangzheng** [comment]
I didn't block this site and its service.

**Comment by sivajipro** [comment]
This domain (ws.pusherapp.com) blocked, cause the app to fail.

**Comment by ookangzheng** [comment]
Okay, Done
ws.pusherapp.com and ws-mt1.pusher.com whitelisted
