### ISSUE TITLE
🚀 iOS/mac OS Big Sur - DoH

### ISSUE THREAD

**Issue by Trepter** [ookangzheng/blahdns#150]
From iOS 14 and macOS Big Sur, the DNS over HTTPS option is possible - it only requires creating a mobileconfig file and applying it. Implement this and add information on how to set it accordingly.

**Many DNSs use this, e.g. here:**
- https://github.com/AhaDNS/setup-guides/blob/master/Apple/iOS.md

**Comment by ookangzheng** [comment]
You can check it out this site: https://encrypted-dns.party/
