### ISSUE TITLE
Decrease in Google Drive Download Speed?🤗 

### ISSUE THREAD

**Issue by jenabaivab** [ookangzheng/blahdns#152]
Hello there!

I recently started using BlahDNS on my windows machine and android. I use YogaDNS on windows to use BlahDNS DoH (Singapore server) from India. 

I had read that changing DNS has no effect on speed(raw speed, not lookup speed). But I noticed that my Google drive download speed dropped from 10MBPS to around 4-5 MBPS. Is there something wrong on my side? It's not a dealbreaker or anything, but can I resolve this in any way or is it just a small price to pay for added privacy/security?

**Comment by ookangzheng** [comment]
Maybe due to the distance between Singapore and India. If google CDN don't have GEO routing policy as primary rule, may cause this issue though I think it does make sense.

**Comment by jenabaivab** [comment]
But by that logic, let's say I use a father server. It should decrease the speed further right? 
I tried the german server, and still got the same download speeds as the Singapore one.

**Comment by ookangzheng** [comment]
From what I learnt is that DNS may resolve Singapore region IP instead of India. Thus, may hurt your speed or latency.
Please do `ping` and `mtr` Google IPs you got. Maybe connection between India and Singapore backbone have some issue or not enough bandwidth.

**Comment by obeho** [comment]
@jenabaivab Could you check using Finland server once and report?

**Comment by jenabaivab** [comment]
I tried checking all the servers after flushing DNS cache each time before changing the dns. I tried downloading the same 1GB file from my google drive.

No BlahDNS/Cloudflare - 10 MBPS average
Blah Singapore - 5.5 MBPS average
Japan - 3.2 MBPS average
Finland - 1.3 MBPS average
Germany - 1.4 MBPS average

I'm guessing I forgot to flush cache before testing germany server yesterday, thats why I got roughly similar speeds. Now the difference is as clear as daylight.

**Comment by ookangzheng** [comment]
Pls try server below

> https://doh.cleanbrowsing.org/doh/security-filter

> https://dns9.quad9.net/dns-query

> https://doh.captnemo.in/dns-query (India server)

> https://jit.ddns.net/dns-query (India server)

**Comment by jenabaivab** [comment]
> https://doh.cleanbrowsing.org/doh/security-filter : 5.4 MB/s

> https://dns9.quad9.net/dns-query : 1.3 MB/s

> https://doh.captnemo.in/dns-query : Timeout (couldn't resolve)

> https://jit.ddns.net/dns-query : 11 MB/s

**Comment by ookangzheng** [comment]
this https://jit.ddns.net/dns-query ?

**Comment by jenabaivab** [comment]
> this https://jit.ddns.net/dns-query ?

Yeah, could I know which service is this?

**Comment by ookangzheng** [comment]
Search it with keyword India 
https://raw.githubusercontent.com/wiki/curl/curl/DNS-over-HTTPS.md

**Comment by jenabaivab** [comment]
Thank you so much. Btw, is there anything that can be done regarding the drive download speeds? Or is that on google?

**Comment by ookangzheng** [comment]
I guess more on Google

**Comment by obeho** [comment]
@ookangzheng Could you please [respond](https://github.com/ookangzheng/blahdns/issues/133#issuecomment-752176136)?

**Comment by ookangzheng** [comment]
Will close this issue from now.
