### ISSUE TITLE
🤗 on iOS 14.3 iMessage can’t send and receive photo using adblock dns

### ISSUE THREAD

**Issue by khfung** [ookangzheng/blahdns#155]
**Question description**
I am currently using the adblock CDN version, but I can’t send and receive photo, is it my setting is wrong? I am using profile to use your dns 
Thanks

**Comment by ookangzheng** [comment]
Hi,

Pls try again

**Comment by ookangzheng** [comment]
@khfung problem solved?

**Comment by khfung** [comment]
@ookangzheng thanks so much, it is working again
