### ISSUE TITLE
about using the DoH in firefox

### ISSUE THREAD

**Issue by shemiie1993** [ookangzheng/blahdns#156]
I did set my custom DoH in the about:config and i have double check the setting. However I still cant see my status reconize as "using DoH" no matter in 1.1.1.1 or on ur website. I think i need some help.
![Screenshot (892)](https://user-images.githubusercontent.com/77489617/104727101-ae564900-572c-11eb-9619-161bf3752396.png)

**Comment by ookangzheng** [comment]
Hi, the correct address of Switzerland DoH is 
- `https://doh-ch.blahdns.com:4443/dns-query` (adblock)
- `https://doh-ch.blahdns.com:4443/uncensor` (no filter)

**Comment by shemiie1993** [comment]
Oh, thanks a lot

**Comment by obeho** [comment]
> If you do network.trr.mode = 3, remember paste this ip address: 45.90.57.121 into network.trr.bootstrapAddress

This step no longer needs to be done in Firefox.

_You are not using BlahDNS_ message on the website, this could happen because of script blocking (you use noscript add-on)
