### ISSUE TITLE
🤗 Will Switzerland DoH resolver be available on port 443 after beta?

### ISSUE THREAD

**Issue by nitrohorse** [ookangzheng/blahdns#157]
Hi! I was just curious as to why the Switzerland DoH resolver is only available over port 4443 and not the typical 443? I think because of this it's currently not usable w/ Firefox's DoH resolver nor in an encrypted DoH configuration profile for Apple devices. Should we expect it to be available on port 443 after exiting beta?

**Comment by ookangzheng** [comment]
Hmm, cuz I planned to configure port 443 for other services on the same server.

**Comment by nitrohorse** [comment]
Oh gotcha -- yeah I tested it in Firefox with [`network.trr.mode` = `3`](https://wiki.mozilla.org/Trusted_Recursive_Resolver#DNS-over-HTTPS_Prefs_in_Firefox) and no requests resolved but do for all other BlahDNS DoH resolvers (would be helpful for someone else to validate this). If this will remain on 4443 maybe adding a note to the website for users to be aware of could help avoid some confusion.

**Comment by ookangzheng** [comment]
<img width="1575" alt="Screen Shot 2021-01-18 at 10 44 07" src="https://user-images.githubusercontent.com/6301735/104866960-b7d4f080-597a-11eb-88e9-89787bd2b6d7.png">

I have tested `network.trr.mode` = `3`while using this mode it works on my Mac (Nightly Firefox)

**Comment by nitrohorse** [comment]
Ah, thanks for validating @ookangzheng -- I embarrassingly wasn't specifying `:4443` in the URL 😓 In Firefox it's working fine but at the moment, an Apple mobileconfig I created isn't resolving requests so I'll need to look into Apple's developer docs to see if specifying the port is supported or not. But otherwise, appreciate your help here. Will close this issue.

**Comment by ookangzheng** [comment]
Cool, ping me if you need further assistant.

**Comment by obeho** [comment]
@ookangzheng Switzerland is beta, only because its reliability is not tested yet? Or any other difference in functionality from the other servers?

**Comment by nitrohorse** [comment]
For reference to answer my own question of why port 4443 doesn't seem to work with Apple mobileconfigs (specifying it in the URL like the Firefox screenshot example)... Apple's [developer docs](https://developer.apple.com/documentation/devicemanagement/dnssettings/dnssettings) state that the URL should be "the URI template of a DNS-over-HTTPS server, as defined in RFC 8484." And if I'm understanding [RFC 8484](https://tools.ietf.org/html/rfc8484) correctly, port 443 is the standard for DoH. Until I learn otherwise I'll assume mobileconfigs using DoH require that resolver to serve over 443 (maybe specifying a different port will be supported in the future).
