### ISSUE TITLE
🤗 adashx.m.taobao.com

### ISSUE THREAD

**Issue by crssi** [ookangzheng/blahdns#158]
Hi guys...

What is known about `adashx.m.taobao.com`?

I can see enormous number of queries from `1plus` android phone.
Is there a reason for it to be on a whitelist?

Occasionally there ale also queries for `fourier.taobao.com` and `msg-global.m.taobao.com`.

Thank you and cheers

**Comment by ookangzheng** [comment]
Domain: `adashx.m.taobao.com`
which may embedded  in some currency converter, blockchain, Alipay some kind of app.

http://www.ekwing.com/doc/downwhitelist?id=140
https://github.com/ATErBion/adblock-mylist/blob/master/adhost.txt

**Comment by crssi** [comment]
I see.

Thank you ❤️
