### ISSUE TITLE
🐛 [dot-ch.blahdns.com-v6] is incomplatible with anonymization.

### ISSUE THREAD

**Issue by Bushwickz** [ookangzheng/blahdns#159]
![blahanon](https://user-images.githubusercontent.com/65140377/106269854-14e26900-61fb-11eb-9bb2-34c7832ecede.jpg)

**Comment by ookangzheng** [comment]
What is your config? Which anonymization provider did u use?

**Comment by Bushwickz** [comment]
> What is your config? Which anonymization provider did u use?

Cryptostorm.is

Sorry for the late response.

**Comment by ookangzheng** [comment]
Can you send me the configuration that you use on Dnscryptv2 proxy?

Thanks

**Comment by Bushwickz** [comment]
..just realized anonymator was mn.nl. Anyways here's the config.

listen_addresses = ['127.0.0.1:53', '[::1]:53']
max_clients = 250
force_tcp = false
timeout = 2000
keepalive = 30
# proxy = 'socks5://127.0.0.1:9050'

# Load-balancing strategy: 'p2' (default), 'ph', 'fastest' or 'random'
lb_strategy = 'p2'
fallback_resolver = '1.1.1.2:53'
ignore_system_dns = false
netprobe_timeout = 30
cache = false
cache_size = 512
cache_min_ttl = 90
cache_max_ttl = 1800
cache_neg_min_ttl = 2
cache_neg_max_ttl = 6

[static]
[static.'dot-ch.blahdns.com']
stamp = 'sdns://AQcAAAAAAAAAETQ1LjkwLjU3LjEyMTo4NDQzIFOE6BRDFCk-Vt0bFAoe8XKtR726F5nIlXKUlT0DTrXHGzIuZG5zY3J5cHQtY2VydC5ibGFoZG5zLmNvbQ'

[static.'dot-ch.blahdns.com-v6']
stamp = 'sdns://AQcAAAAAAAAAFVsyYTA1Ojk0MDY6OjE3NV06ODQ0MyBThOgUQxQpPlbdGxQKHvFyrUe9uheZyJVylJU9A061xxsyLmRuc2NyeXB0LWNlcnQuYmxhaGRucy5jb20'

[anonymized_dns]
routes = [
 { server_name='dot-ch.blahdns.com', via=['sdns://gRI4My43OC4xMjAuMjI3Ojg0NDM'] },
 { server_name='dot-ch.blahdns.com-v6', via=['sdns://gStbMjAwMToxOWYwOjUwMDE6Y2JiOjU0MDA6M2ZmOmZlMDc6ZjcwZF06NDQz'] },
]

**Comment by ookangzheng** [comment]
Sorry my bad. 
I have miss configured firewall. Now every should work as expected.

Screenshot 
![Screen Shot 2021-02-04 at 10 59 40](https://user-images.githubusercontent.com/6301735/106839002-43b77e00-66d8-11eb-96cd-6b4f717c03a4.png)

**Comment by Bushwickz** [comment]
> Sorry my bad.
> I have miss configured firewall. Now every should work as expected.
> 
> Screenshot
> ![Screen Shot 2021-02-04 at 10 59 40](https://user-images.githubusercontent.com/6301735/106839119-8711ec80-66d8-11eb-855f-00fa77c67880.png)

Got it! Thanks.
