### ISSUE TITLE
🤗 Website says I'm not using Blahdns and Encrypted/SNI Question?

### ISSUE THREAD

**Issue by CyberPunkInterface** [ookangzheng/blahdns#160]
>Blahdns website says im not using blahdns, but my resolver is currently connected?<

I have ran many different browser dns test and they show im connected to blahdns.

**how do I fix this?**

>Also is Blahdns not encrypted? and is SNI encryption supported?<

 **Or is SNI encryption a browser issue?**

**Comment by ookangzheng** [comment]
Could you try again. 

If you still encounter this issue, please copy paste this command into your terminal.

```bash
❯ nslookup test.blahdns.com
Server:		::1
Address:	::1#53

Non-authoritative answer:
Name:	test.blahdns.com
Address: 216.27.7.29
```
If it return an IP, then you're currently connected to BlahDNS.

**Comment by obeho** [comment]
_You are not using BlahDNS_ message on the website, could happen because of script blocking (adblockers)

**Comment by CyberPunkInterface** [comment]
>If you still encounter this issue, please copy paste this command into your terminal.

Yeah it was My DNS-over TLS Resolver Problem and a Windows 10 Issue.

>You are not using BlahDNS message on the website, could happen because of script blocking (adblockers)

Ok Thanks this helped.

**Comment by yutayu** [comment]
now , Website says it lol
I use japan dnscrypt server, dns query seems correct.
