### ISSUE TITLE
🐛 Whitelist assets.npo-data.nl

### ISSUE THREAD

**Issue by mmwvh** [ookangzheng/blahdns#162]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
assets.npo-data.nl is necessary for the NPO app to function

**To Reproduce**

1. In the NPO app (iOS, android, WebOS), content does not start to play

**Expected behavior**
In the NPO app, content starts to play

**Logs (optional)**
n/a

**Server if applicable):**

- OS: Debian 10
- Hosting provider: RaspberryPI

**Client (if applicable):**

- Device: Apple, Android, LG TV]
- OS: iOS13, Android 10, WebOS 6
- Client: Dnscrypt-v2
- Protocol: Dnscrypt

**Comment by ookangzheng** [comment]
Done ~~

**Comment by mmwvh** [comment]
Thank you for the fast response!

Sorry to bother again. After assets.npo-data.nl was whitelisted, a new domain is blocking the NPO app from functioning, i.e. topspin.npo.nl.

Would you whitelist topspin.npo.nl as well?

Thank you

**Comment by ookangzheng** [comment]
Done ~~
