### ISSUE TITLE
[🤗 Question] DNS makes internet "break"?

### ISSUE THREAD

**Issue by AndrewDaGuy** [ookangzheng/blahdns#164]
Setting the DNS (`Japan`/`Germany`) make's my internet "break" where it seems to basically act like there's no DNS. Checked the up-time status and everything seems fine to me.

### Settings
```js
DNS1: 139.162.112.47 (Japan)
DNS2: 78.46.244.143  (Germany)

---
IPv6 DNS

DNS1: 2400:8902::f03c:92ff:fe27:344b (Japan)
DNS2: 2a01:4f8:c17:ec67::1           (Germany)
```

### Additional info 
On my Linux distro, it appears like this
```js
139.162.112.47 78.46.244.143
```
However on ios (nothing):
```void


```

#### Using Cloudflare
Linux:
```js
1.1.1.1 1.0.0.1
```
---

ios (Auto):
```js 
1.1.1.1
1.0.0.1
```
---

**Comment by ookangzheng** [comment]
What kind of protocol do you use?

**Comment by AndrewDaGuy** [comment]
> What kind of protocol do you use?

2.4 band: `802.11 b/g/n mixed` (Linux)
5 band: `802.11 a/n/ac mxied` (ios)

**Comment by ookangzheng** [comment]
> > What kind of protocol do you use?
> 
> 2.4 band: `802.11 b/g/n mixed` (Linux)
> 5 band: `802.11 a/n/ac mxied` (ios)

Sorry, I mean DNS protocol
Plain text UDP (port 53) < server doesnt support > 
or 
DNS-over-HTTPS, DNS-over-TLS, DNS-over-QUIC, DNSCryptv2

**Comment by AndrewDaGuy** [comment]
> > > What kind of protocol do you use?
> > 
> > 
> > 2.4 band: `802.11 b/g/n mixed` (Linux)
> > 5 band: `802.11 a/n/ac mxied` (ios)
> 
> Sorry, I mean DNS protocol
> Plain text UDP (port 53) < server doesnt support >
> or
> DNS-over-HTTPS, DNS-over-TLS, DNS-over-QUIC, DNSCryptv2

Seems im using `UDP` as I don't see any of those listed on my settings.

**Comment by ookangzheng** [comment]
Ya, unfortunately BlahDNS has drop support for unencrypted DNS
I'd suggest to use DNScloak on iOS (Dnscrypt, DoH) or Nebulo, PersonalDNSfilter on Android
If you have AdGuard installed, it is also compatible with BlahDNS (DNSCrypt, DoH, DoT, DoQ)

On Linux, you can use DoT (DNS-over-TLS) with `systemd`
Example
```bash
nano /etc/systemd/resolved.conf

[Resolve]
DNS=dot-jp.blahdns.com dot-de.blahdns.com
FallbackDNS=9.9.9.9 1.0.0.2
Domains=~.
#LLMNR=no
#MulticastDNS=no
DNSSEC=yes
DNSOverTLS=yes
```
