### ISSUE TITLE
🤗 How to connect to the SG server with IP?

### ISSUE THREAD

**Issue by eiden2233** [ookangzheng/blahdns#165]
Setting the DNS on Asus router with IP worked with other DNS providers but when I tried 192.53.175.149, internet stopped working.

**Comment by ookangzheng** [comment]
BlahDNS dosent support plain DNS resolution, Pls consider DNSCrypt, DoH, DoT, DoQ instead.
Otherwise, I'd recommend `94.140.14.14` (Adguard)
