### ISSUE TITLE
🚀 Include Adguard Mobile Hosts + Polish regional hosts

### ISSUE THREAD

**Issue by TrashPandaCodingGarbage** [ookangzheng/blahdns#166]
Good morning, 

First, I really appreciate BlahDNS. It is working flawlessly for me. The hosts choice is interesting, and it is able to block the majority of the trackers over the internet. 

1. On my personal device I am using  AdGuard Mobile Ads and AdGuard Mobile Tracking and Spyware converted hosts [from this repo ](https://github.com/r-a-y/mobile-hosts), which are crafted specifically for mobile ads. This host list is enough to block 99% of nasty ads on our mobile device. I think those hosts would make a great addition to BlahDNS. 

2. I have noticed that on some Polish websites ads are still displayed. Most Polish people just install [this filter](https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt) on their Pi. It's the most popular, and the ultimate choice for ads on Polish websites. Is it possible to include it?

Thank you once again for this project. I will donate this month.

**Comment by ookangzheng** [comment]
Polish filter: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt has been added.  Also, feedback needed
