### ISSUE TITLE
🤗 some website not accessible with DNS-over-TLS

### ISSUE THREAD

**Issue by alant54** [ookangzheng/blahdns#167]
**Question description**

Hello i was trying your dns and i see that some website like https://hub.docker.com/ and other was not accessible when i use the dns.
Do you know where this "problem" may come from ?

**Comment by Gontier-Julien** [comment]
I've got the same issue with some domain, and i checked if it is on the blacklist but it isn't. So maybe it is because it use Quad9 as it upstream.
It will be great if Blahdns had a uncensored option.

**Comment by alant54** [comment]
i have try the dns of quad9 and i dont have this problem but the real quesiton is i dont see a reason why the dns is blocking a website like docker.. there is no sense

**Comment by ookangzheng** [comment]
Currently, both servers are not in heavy load, therefore all DNS resolution will be resolved locally. 
I try just now `hub.docker.com` isn't in the filter list, so please give it a try. 

Thanks

> **Question description**
> 
> Hello i was trying your dns and i see that some website like https://hub.docker.com/ and other was not accessible when i use the dns.
> Do you know where this "problem" may come from ?

**Comment by ookangzheng** [comment]
> I've got the same issue with some domain, and i checked if it is on the blacklist but it isn't. So maybe it is because it use Quad9 as it upstream.
> It will be great if Blahdns had a uncensored option.

Currently, BlahDNS do have an uncensored option (DNS-over-HTTPS)

1.  https://doh-jp.blahdns.com/uncensor (-jp, -sg, -de, -fi, -ch)
2. https://doh1.blahdns.com/uncensor (CDN)
3. https://doh2.blahdns.com/uncensor (CDN)

**Comment by Gontier-Julien** [comment]
Thanks it seem to be resolving it again!
Just a quick question, is there a possibility to have an uncensored version of Blahdns but with DoT ? It will be awesome ^^

**Comment by ookangzheng** [comment]
If so, I gonna set up another VM to provide uncensored DoT.
Otherwise, I gonna use another port for uncensored DoT on the same machine.

**Comment by Gontier-Julien** [comment]
> If so, I gonna set up another VM to provide uncensored DoT.
> Otherwise, I gonna use another port for uncensored DoT on the same machine.

Thank you very much men, your work is amazing! ^^
but if i'm not wrong you can create another VM and make the name of the domain different so you cloud have it on the same port. Right?

**Comment by ookangzheng** [comment]
> > If so, I gonna set up another VM to provide uncensored DoT.
> > Otherwise, I gonna use another port for uncensored DoT on the same machine.
> 
> Thank you very much men, your work is amazing! ^^
> but if i'm not wrong you can create another VM and make the name of the domain different so you cloud to have it on the same port. Right?

Ya, exactly.
Unfortunately, recently I do not have enough budget for VM. 

Thanks for your understanding.

**Comment by Gontier-Julien** [comment]
> > > If so, I gonna set up another VM to provide uncensored DoT.
> > > Otherwise, I gonna use another port for uncensored DoT on the same machine.
> > 
> > 
> > Thank you very much men, your work is amazing! ^^
> > but if i'm not wrong you can create another VM and make the name of the domain different so you cloud to have it on the same port. Right?
> 
> Ya, exactly.
> Unfortunately, recently I do not have enough budget for VM.
> 
> Thanks for your understanding.

No worry ^^
It was only a proposition after all, so no need to rush it or anything.

**Comment by ookangzheng** [comment]
I gonna close this ticket from now.
