### ISSUE TITLE
🤗 Unable to access blahdns.com.

### ISSUE THREAD

**Issue by SkyYkb** [ookangzheng/blahdns#169]
Well, hello everyone.
I'm now having issue accessing blahdns.com. This is how the issue appears:
- I open https://blahdns.com;
- I get Cloudflare Error 1020 - Access denied.
My Cloudflare Ray ID is: `62f9b8cc8eb13610`.

And seems like I can't access BlahDNS Japan server either.
How do I solve this?
Thanks.

**Comment by ookangzheng** [comment]
Sorry, Let me have a look.

**Comment by SkyYkb** [comment]
Still returns Cloudflare 1020, with my Ray ID `62fd3a1ada6342ab`.
Is it an automatic protection by Cloudflare, I guess? But I've tried to restart my modem to get a new IP address, and it still doesn't work.
Anyway, I just wanted to tell you guys the problem. My ISP is China Telecom Zhejiang Branch.

**Comment by ookangzheng** [comment]
Sorry for the late reply, pls try again. 
Cloudflare is blocking some china IP due to some DDoS attack. I flushed the blacklist IP. It should be okay.
