### ISSUE TITLE
Add non-paypal option for donations on LiberaPay

### ISSUE THREAD

**Issue by Silmathoron** [ookangzheng/blahdns#171]
First of all, thanks a lot for that very nice project.
I would love to support it via a donation on LiberaPay, unfortunately I don't have a PayPal account (and I do unfortunately not intend to make one).
Is there any way you could make donation available via other means there? (I think there is at least bank transfer).
I asked LiberaPay whether there was anything they could do and they told me that other people had already ask them the same, so there might be others like me that would like to donate but currently cannot.

**Comment by ookangzheng** [comment]
Hi @Silmathoron 

LiberaPay cannot support Stripe or bank transfer due to the owner's residential address not belong to the US or EU.
Though I do have Transferwise or Cryptocurrencies as an alternative.

PM me for more information. 

Best regards

**Comment by Silmathoron** [comment]
Ah, OK, thanks for that clarification, I did not get the information from LiberaPay, I'll check with them whether they are aware of this issue.

**Comment by ookangzheng** [comment]
How abt Pioneer or Transfer wise?
They have a bank transfer option.
