### ISSUE TITLE
🐛 Whitelist MS Azure functionality

### ISSUE THREAD

**Issue by mmwvh** [ookangzheng/blahdns#172]
**Checklist**

- [ x ] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [ x ] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [ x ] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
I would like to request to whitelist the following sites because it blocks MS Azure functionality
- api.loganalytics.io
- breeze.aimon.applicationinsights.io

Thank you, you are doing amazing work!

**Comment by ookangzheng** [comment]
Found in `abp.osid.nl`, fixed

![Screen Shot 2021-04-23 at 17 55 56](https://user-images.githubusercontent.com/6301735/115854799-2f745900-a45d-11eb-82ca-59936a1ad6f0.png)
![Screen Shot 2021-04-23 at 17 55 08](https://user-images.githubusercontent.com/6301735/115854808-326f4980-a45d-11eb-9f1e-d6a1b550f3e9.png)

**Comment by mmwvh** [comment]
Thank you for your fast response!
