### ISSUE TITLE
🐛 Whitelist valimail

### ISSUE THREAD

**Issue by mmwvh** [ookangzheng/blahdns#173]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
I am unable to register to the site valimail, and I notice that see.valimail.com is being blocked. Would you please whitelist see.valimail.com.

Thank you

**Comment by ookangzheng** [comment]
Fixed
