### ISSUE TITLE
🤗 10 sec to resolve at dnscrypt-jp-blahdns-ipv4

### ISSUE THREAD

**Issue by yutayu** [ookangzheng/blahdns#174]
**Question description**
When I use blahdns-jp-doh, quick to revolve dns.
but  dnscrypt-jp-blahdns-ipv4 takes around 10 sec to resolve dns.

**Comment by yutayu** [comment]
I use newest dnscrypt-proxy on Manjaro.

**Comment by ookangzheng** [comment]
Please try `force_tcp = true`

**Comment by yutayu** [comment]
It works , but I want to use udp.lol

**Comment by ookangzheng** [comment]
Ya, I noticed this issue this few days ago though I'm busy this 2 months.
Pls use `stubby` + DoT or `dnscrypt` + `DoH` for better performance. 

Note: on Android 11 phone it works fine (AdGuard Pro), takes 2.5 sec on Mac and Linux server via `dnscrypt`

**Comment by yutayu** [comment]
@ookangzheng 
I changed dnscrypt-proxy unbound dot. 
Never mind. :)

**Comment by ookangzheng** [comment]
Please try again and let me know. 
I changed dnscrypt with entire new keys and server-side software

https://github.com/ookangzheng/blahdns/blob/master/client-conf/dnscrypt/dnscrypt-proxy.toml

**Comment by yutayu** [comment]
[2021-04-29 16:22:19] [WARNING] [dnscrypt-jp-blahdns-ipv4] Incorrect signature for provider name: [2.dnscrypt-cert.blahdns.com.]

I tried.
It doesn't work at all.

**Comment by yutayu** [comment]
[2021-04-29 16:22:19] [WARNING] [dnscrypt-jp-blahdns-ipv4] Incorrect signature for provider name: [2.dnscrypt-cert.blahdns.com.]

I tried.
It doesn't work at all.

**Comment by ookangzheng** [comment]
Again, please. 
I forgot to update `2.dnscrypt-cert.blahdns.com` domain

**Comment by yutayu** [comment]
dnscrypt-proxy[8604]: [2021-04-29 16:41:27] [WARNING] [dnscrypt-jp-blahdns-ipv4] Incorrect signature for provider name: [2.dnscrypt-cert.blahdns.com.]
 dnscrypt-proxy[8604]: [2021-04-29 16:41:27] [ERROR] No useable certificate found

**Comment by ookangzheng** [comment]
Which software are you using? 
via Unbound?

**Comment by yutayu** [comment]
Maybe stamp was changed.
It works with low latency, Great job and Thanks :)

**Comment by ookangzheng** [comment]
Ya, the entire DNS Stamp has changed. 
I submitted a Pull request and waiting for approval which included the latest DNS Stamp. 

Sorry for that.

**Comment by yutayu** [comment]
Never mind :)
