### ISSUE TITLE
dnscrypt-jp-blahdns-ipv4  Incorrect signature for provider name

### ISSUE THREAD

**Issue by advaithm** [ookangzheng/blahdns#175]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
dnscrypt-proxy gives warning about  blahdns jp. on start dnscrypt gives a warning about a incorrect signature
```
Apr 29 06:15:12 BadDragon dnscrypt-proxy[14833]: [2021-04-29 06:15:12] [WARNING] [dnscrypt-jp-blahdns-ipv4] Incorrect signature for provider name: [2.dnscrypt-cert.blahdns.com.]
```

**To Reproduce**

1. fresh install of dnscrypt-proxy
2. add `'dnscrypt-jp-blahdns-ipv4'` to server names
3. start dnscrypt-proxy and check the logs

**Expected behavior**
I excepted blahdns-jp to  have no issues and dnscrypt proxy to use it

**Server if applicable):**

- OS: Archlinux Arm
- raspberry pi 4

**Comment by ookangzheng** [comment]
I already submit a pull request https://github.com/DNSCrypt/dnscrypt-resolvers/pull/478
If you can't wait, please consider using this configuration below.

```
server_names = ['blahdns-jp-dnscrypt-v4']
listen_addresses = ['127.0.0.1:53', '[::1]:53']
max_clients = 300
force_tcp = false
timeout = 3000
keepalive = 30

lb_strategy = 'p2'
fallback_resolver = '9.9.9.9:53'
ignore_system_dns = true
netprobe_timeout = 30
cache = false
cache_size = 512
cache_min_ttl = 90
cache_max_ttl = 1800
cache_neg_min_ttl = 10
cache_neg_max_ttl = 90

[static]
# Japan Dnscrypt
[static.'blahdns-jp-dnscrypt-v4']
stamp = 'sdns://AQMAAAAAAAAAEzEzOS4xNjIuMTEyLjQ3Ojg0NDMghROpa8Tgg0uVDWO1AujT4tVNBJZrJgKTNOkHHboj_CsbMi5kbnNjcnlwdC1jZXJ0LmJsYWhkbnMuY29t'
```

**Comment by ookangzheng** [comment]
@advaithm problem solved?

**Comment by advaithm** [comment]
yeah this is solved you
