### ISSUE TITLE
Whitelist oscp.apple.com

### ISSUE THREAD

**Issue by blu-e-man** [ookangzheng/blahdns#176]
Checklist

- [x] I read the README
- [x] I read the FAQ
- [x] I searched the issues

**Describe the issue**

Unfortunately [ocsp.apple.com](url) is blocked. It's the Apple certificate validation, used to validate digital certificates for Apple software and content.
Could you whitelist the domain? 

Thank you

**Comment by ookangzheng** [comment]
I blocked this on purpose. 
It hurt privacy and track user 
Source: https://sneak.berlin/20201112/your-computer-isnt-yours/

**Comment by blu-e-man** [comment]
To me it looks more like a security feature. 
It can be used to check whether Apple Developer certificates have been revoked. 

https://blog.jacopo.io/en/post/apple-ocsp/

**Comment by AndrewDaGuy** [comment]
This also seems to be blocked software updates :(

**Comment by ookangzheng** [comment]
May I know which server are you using?
@blu-e-man @AndrewDaGuy
