### ISSUE TITLE
Snapchat "Bitmoji" & "Stickers" not loading properly🐛 

### ISSUE THREAD

**Issue by f0null** [ookangzheng/blahdns#179]
**Checklist**

- [x ] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [ x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x ] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Using BlahDNS, the Snapchat "Bitmoji" Service is not working properly. Also the "Stickers" aren't showing up

**To Reproduce**

1. Use BlahDNS
2. Open the "Snapchat" App on iOS and open the "Map". Or try to apply a Sticker. Some are marked with a "!"

**Expected behavior**
Using Cloudflare DNS, every Sticker and "Bitmoji" shows up.

**Logs (optional)**
If applicable, add logs or screenshots to help explain your problem.
![photo_2021-05-17_23-02-36](https://user-images.githubusercontent.com/84352256/118556282-fa111180-b763-11eb-9a72-91c8e68697ea.jpg)
![photo_2021-05-17_23-02-42](https://user-images.githubusercontent.com/84352256/118556288-fd0c0200-b763-11eb-8c64-e74f5b3ccbc0.jpg)

If you can reproduce the issue, please describe it below.

**Server if applicable):**
 -

**Client (if applicable): -

- Device: iPhone
- OS: 14.6
- Client: iPhone 12 Pro max
- Protocol: DoH / DoT / Quic 

**Additional context**
A Subdomain for Snapchat is probably blocked.

**Comment by ookangzheng** [comment]
Sorry, I don't use Snapchat at all. I can't help you out 

Can you provide AdGuard Pro (iOS) screenshot?
Open Snapchat and choose emoji immediately and capture the logs of SnapChat requested.

Thanks

**Comment by f0null** [comment]
Hey, thank you for your response.

I'm not using AdGuard on iOS. I'm using AdGuard Home as a DNS level Ad-Blocker.
Still, I managed to extract the following domains, which seem to interact with the Snapchat application:

images.bitmoji.com
s.sc-cdn.net
gcs.sc-cdn.net
bolt-gcdn.sc-cdn.net
ct-giphy.sc-cdn.net
aws.api.sc-gw.com
topic-sticker-vending.snapchat.com
europe-west1-gcp.api.snapchat.com
us-east1-aws.api.sc-gw.com
internal-api.snapkit.com
aws.api.snapchat.com
app.snapchat.com
snap.api.mapbox.com
snap.events.mapbox.com

sc-cdn.net is the "Snapchat CDN" Domain.
sc-gw.com is a "Snapchat Gateway"
snapchat.com and snapkit.com are Snapchat Domains
mapbox.com is the domain used by the Map Service within the App.

images.bitmoji.com results in "0.0.0.0" when trying to be resolved by blahDNS as logged by AdGuard

![image](https://user-images.githubusercontent.com/84352256/118696234-621c3200-b80e-11eb-83da-702e2fa89a9d.png)
The Rule is in place to explicitly allow this domain, stated by "@@||"

**Comment by ookangzheng** [comment]
Should be fixed. Pls try again

**Comment by f0null** [comment]
Hello,

Thank you for your Quic help! 
It's working flawlessly now.
