### ISSUE TITLE
🚀 whitelist please adskeeper.co.uk

### ISSUE THREAD

**Issue by What-Zit-Tooya** [ookangzheng/blahdns#180]
**Is your feature request related to a problem?**
The problem is if  `adskeeper.co.uk` blocked, some anti adblock filter can not use the rules like this issue https://github.com/uBlockOrigin/uAssets/issues/9165

**Describe the solution you'd like**
Whitelist it

**Describe alternatives you've considered**

**Additional context**
`adskeeper.co.uk` is a part of Peter Lowe's adservers, if there is using filter to using it, it need to be whitelisted

**Comment by ookangzheng** [comment]
Should be fix now

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Should be fix now

Thx , fixed now. :)
