### ISSUE TITLE
Genshin Impact: Update Tab not loading🐛 

### ISSUE THREAD

**Issue by f0null** [ookangzheng/blahdns#181]
**Checklist**

- [ x ] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [ x ] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [ x ] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Genshin Impact URL is blocked which is used to contact Update Server

**To Reproduce**

1. Open the Game
2. In the Menu, navigate to the Update tab

**Expected behavior**
A pop Up Windows should be opened, doesn't happen.

If you can reproduce the issue, please describe it below.

**Client (if applicable):**

- Device: Windows 
- OS:  Windows 10
- Client: AdGuard Home
- Protocol: DoH, DoT, DoQ

**Additional context**
The problem should be resolved by allowing "log-upload-os.mihoyo.com" as seen as in the attached Screenshots. Using Cloudflare DNS, the Update Tab is working fine.
BlahDNS:
![Capture](https://user-images.githubusercontent.com/84352256/120042777-08381b00-c00b-11eb-8ca9-c65ea3fcbb64.PNG)

Expected via Cloudflare:
![Capture2](https://user-images.githubusercontent.com/84352256/120042805-1423dd00-c00b-11eb-872e-2f067bdafe66.PNG)

Thank you for your hard work!

**Comment by ookangzheng** [comment]
Fixed

**Comment by f0null** [comment]
Thank you, working now!
