### ISSUE TITLE
🚀 Whitelist zhuti.xiaomi.com

### ISSUE THREAD

**Issue by What-Zit-Tooya** [ookangzheng/blahdns#182]
**Is your feature request related to a problem?**
Whitelist `zhuti.xiaomi.com` and any zhuti server (if any)

**Describe the solution you'd like**
Whitelist that pls, that is theme server for Xiaomi Phone's

**Describe alternatives you've considered**

**Additional context**

**Comment by ookangzheng** [comment]
fixed

**Comment by What-Zit-Tooya** [comment]
Nice, thanks
