### ISSUE TITLE
https://stats.blahdns.com/ is down.🐛 

### ISSUE THREAD

**Issue by yutayu** [ookangzheng/blahdns#183]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
A clear and concise description of what the issue is.
https://stats.blahdns.com/ is down.
**To Reproduce**
Access it .
1. ...
2. ...

**Expected behavior**
we can watch it .
**Logs (optional)**
If applicable, add logs or screenshots to help explain your problem.

If you can reproduce the issue, please describe it below.

**Server if applicable):**

- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. Vultr, AWS, OpenWRT, RaspberryPI]

**Client (if applicable):**
firfox-esr 
- Device: [e.g. iPhone, Android, Linux, Windows]
- OS: [e.g. iOS13, Android 10, Debian 10, Windows 10]
- Client: [e.g. Nebulo, Unbound, Bind9, Dnscrypt-v2, Intra]
- Protocol: [e.g. DoH, DoT, Dnscrypt]

**Additional context**

**Comment by ookangzheng** [comment]
Its not down, technically though. Uptimerobot they not offer free plan anymore. 
So far I don't have plan to upgrade to paid plan at this moment.

**Comment by yutayu** [comment]
okok , np.
