### ISSUE TITLE
Allow app.powerbi.com🐛 

### ISSUE THREAD

**Issue by mmwvh** [ookangzheng/blahdns#185]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
The Microsoft PowerBI app is blocked. Would you whitelist: app.powerbi.com

Thank you, you are doing an amazing job!

**Comment by ookangzheng** [comment]
Fixed
