### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by mmwvh** [ookangzheng/blahdns#188]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
LinkedIn is blocked. Can you add www.linkedin.com to the whitelist? Thank you.

**Comment by ookangzheng** [comment]
Found on Kris phishing blocklist. Should be fixed now
