### ISSUE TITLE
whitelist pls🐛 

### ISSUE THREAD

**Issue by What-Zit-Tooya** [ookangzheng/blahdns#189]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
`au.ff.avast.sec.miui.com` is blocked, i can not update avast antivirus database on xiaomi

**To Reproduce**

1. open xiaomi security app
2. go to scan virus, select option on top righht corner
3.  update avast database

**Expected behavior**
Should not be blocked

**Logs (optional)**
If applicable, add logs or screenshots to help explain your problem.

If you can reproduce the issue, please describe it below.

**Server if applicable):**

- OS: [Android 11]
- Hosting provider (if applicable): [e.g. Vultr, AWS, OpenWRT, RaspberryPI]

**Client (if applicable):**

- Device: [android]
- OS: [11]
- Client: [Adguard]
- Protocol: [Dnscrypt v2]

**Additional context**

**Comment by ookangzheng** [comment]
Wow, I Xiaomi had security app @@ 
Fixed

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Wow, I Xiaomi had security app @@
> Fixed

almost chinese phone have built in security app. Like oppo , xiaomi, etc, and they usually use avast or avl anti virus.

thanks, now working good.
