### ISSUE TITLE
🐛 Alipay is blocked

### ISSUE THREAD

**Issue by baddigestion** [ookangzheng/blahdns#190]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Alipay app and Alipay payment in Taobao is blocked.

**To Reproduce**

1. Try to login Alipay
2. or during check out in Taobao

**Expected behavior**
App or payment page should load.

**Client (if applicable):**

- Device: [Android]
- OS: [Android 11]
- Client: [Android Private DNS]
- Protocol: [DoT]

**Additional context**
Not sure how to capture requests on Android.

**Comment by ookangzheng** [comment]
Fixed
