### ISSUE TITLE
Does Singapore Server down?🤗 

### ISSUE THREAD

**Issue by What-Zit-Tooya** [ookangzheng/blahdns#191]
I can't connect into it

**Comment by ookangzheng** [comment]
Which protocol

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Which protocol

DOH and DNScrypt v2
DOH on my phone, DNScrypt v2 on adguard home
![Screenshot_20210708-174612](https://user-images.githubusercontent.com/9832875/124909656-ede35b00-e014-11eb-982f-ec463fea932b.png)

**Comment by What-Zit-Tooya** [comment]
@ookangzheng DOT  `dot-sg.blahdns.com`  also down, recentyl checked on Android 10

**Comment by ookangzheng** [comment]
Everything works on my server and phone (iOS, Android). 
DoH, DoT, Dnscryptv2

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Everything works on my server and phone (iOS, Android).
> DoH, DoT, Dnscryptv2
> 
> DoH test: https://doh-sg.blahdns.com/dns-query?name=okz.io (Should return json object)
> 
> DoT test: `kdig okz.io +tls @dot-sg.blahdns.com`
> 
> <img alt="Screen Shot 2021-07-08 at 20 15 37" width="788" src="https://user-images.githubusercontent.com/6301735/124919924-5c321880-e029-11eb-91f1-aeaea4202fd8.png">
> 
> Dnscryptv2 on Mac machine
> 
> <img alt="Screen Shot 2021-07-08 at 20 18 29" width="1103" src="https://user-images.githubusercontent.com/6301735/124920292-c34fcd00-e029-11eb-89cb-4c28fd16557b.png">

Seems works now, dunno what happen on my side.
Thanks for clarify.

**Comment by What-Zit-Tooya** [comment]
@ookangzheng seems down right now, can't making connection from adguard
