### ISSUE TITLE
Blacklist issue 🐛 

### ISSUE THREAD

**Issue by obeho** [ookangzheng/blahdns#194]
`itgiblean.com` domain is in [oisd](https://dbl.oisd.nl/basic) list (added on June 27 '21), and absent in either of your personal whitelists. Yet, it isn't being blocked. @ookangzheng What went wrong here?

![](https://user-images.githubusercontent.com/71698631/125458100-22c04891-20b9-411e-9860-4e9eec4e6c36.png)

**Comment by ookangzheng** [comment]
Let me manually start update filters cronjob.

Filter usually update twice a day  every 6 hours.
