### ISSUE TITLE
Blacklist issue 🐛 

### ISSUE THREAD

**Issue by obeho** [ookangzheng/blahdns#196]
`kinkledunendly.com` domain is in [oisd](https://dbl.oisd.nl/basic) list (added on July 18 '21). It isn't being blocked. @ookangzheng 
#194 rectified?

![ssss](https://user-images.githubusercontent.com/71698631/126535386-2e6134ef-4f86-49d9-ac95-9d30af3673b4.png)

**Comment by ookangzheng** [comment]
Hmm, so wired.. Fixed now
