### ISSUE TITLE
Whitelist some servers🐛 

### ISSUE THREAD

**Issue by What-Zit-Tooya** [ookangzheng/blahdns#197]
**Checklist**

- [ ] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [ ] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [ ] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Whitelist `pagead2.googlesyndication.com` Breakage some site with anti-adblock feature like this https://github.com/uBlockOrigin/uAssets/issues/9604

**To Reproduce**

1. ...
2. ...

**Expected behavior**
It get whitelisted

**Logs (optional)**
If applicable, add logs or screenshots to help explain your problem.

If you can reproduce the issue, please describe it below.

**Server if applicable):**

- OS: [Windows 10]
- Hosting provider (if applicable): [e.g. Vultr, AWS, OpenWRT, RaspberryPI]

**Client (if applicable):**

- Device: [Firefox]
- OS: [Windows 10]
- Client: [DNScrypt]
- Protocol: [Dnscrypt]

**Additional context**

**Comment by ookangzheng** [comment]
Actually from what I tested domain `pagead2.googlesyndication.com` is a dead domain.

<img width="647" alt="Screen Shot 2021-07-24 at 13 50 20" src="https://user-images.githubusercontent.com/6301735/126858860-72071e24-c4fe-4b0f-8a23-2dc495d53d16.png">

**Comment by What-Zit-Tooya** [comment]
Ahh..right , 
Some ads server this also need to be whitelisted, it triggered anti adblock, even if anti adblock filter already loaded
`crunchyroll.adtrackers.net`
`serve.adtrackers.net`
`crunchyroll.bannertrack.net`
`crunchyroll.adnetasia.com`
`cst.cstwpush.com`
`yahoo.adnetasia.com`

Those come from `nekopoi app`, i tried to block them, but that will trigger anti adblock,
This commit https://github.com/Yuki2718/adblock/commit/dd72ad66c8b25cabb891ee8449d15b33feb27a89 already whitelist them

**Comment by ookangzheng** [comment]
Whitelisted
