### ISSUE TITLE
DNS TLS Cannot resolve domain name for unbound v1.7.3 

### ISSUE THREAD

**Issue by wuyanteng** [ookangzheng/blahdns#2]
unbound  Partial configuration：

forward-zone:
    name: "."
    forward-addr: 108.61.201.119@853
    forward-ssl-upstream: yes
    forward-first: yes

**Comment by ookangzheng** [comment]
@wuyanteng The problem has been solved. 
I disabled OpenNIC TLD, due to resolver can't resolve DNSSEC

**Comment by wuyanteng** [comment]
I have not enabled DNSSEC, and I don't think that commenting out the include configuration will solve the problem.

Also, my current configuration, using 1.1.1.1@853 or 9.9.9.9@853 is normal, now I can only question the use of blahdns

**Comment by ookangzheng** [comment]
It works for me though, I tested on with Unbound latest version on my VPS though.
Please try again
![2018-08-04 01 05 37](https://user-images.githubusercontent.com/6301735/43655806-a7f00a2c-9782-11e8-824b-aca1576235cd.gif)

**Comment by wuyanteng** [comment]
The Japanese node's DNS latency is very large, and the resolution in China fails. It can be resolved by using another DNS in Frankfurt, Germany. Moreover, when DNSSEC is enabled, the domain name resolution delay can only be increased, and the result is basically unbearable.

Abandoning the use, it is planned to close the DNSSEC check function and directly call the port 853 of Taiwan 101.101.101.101, which is very fast!

Thank you!

**Comment by ookangzheng** [comment]
Okay. Ya China blacklisted a lot of VPS IP this day. Yap, Taiwan 101.101.101.101 will be a good option too.
