### ISSUE TITLE
Confusion regarding configuration in stuby

### ISSUE THREAD

**Issue by Techguyprivate** [ookangzheng/blahdns#20]
Sorry for the question. I am a noob. What should be the configuration for stuby dns for ubuntu ? 

Should it be like this, below ? 

# Blahdns
  - address_data: 108.61.201.119
    tls_port: 853
    tls_auth_name: "dns.jp.blahdns.com"

  - address_data: 159.69.198.101
    tls_port: 443
    tls_auth_name: "dot-de.blahdns.com"

  Or do I need to write anything else? Is the tls_port line required? Huge Thanks anyway.

**Comment by ookangzheng** [comment]
If you want to use default port 853, then you don't need to specify the port number.
Port 443 is just the alternative like while you in office, school network env have very strict firewall controlled rules.
```bash
address_data: 108.61.201.119
tls_port: 853
tls_auth_name: "dot-jp.blahdns.com"

address_data: 159.69.198.101
tls_port: 853
tls_auth_name: "dot-de.blahdns.com"
```

**Comment by Techguyprivate** [comment]
Thank you. Closing it.
