### ISSUE TITLE
The Server Status dont work

### ISSUE THREAD

**Issue by lolly223** [ookangzheng/blahdns#201]
**Checklist**

- [ ] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [ ] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [ ] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Logs (optional)**
If applicable, add logs or screenshots to help explain your problem.

If you can reproduce the issue, please describe it below.

**Server if applicable):**

- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. Vultr, AWS, OpenWRT, RaspberryPI]

**Client (if applicable):**

- Device: [e.g. iPhone, Android, Linux, Windows]
- OS: [e.g. iOS13, Android 10, Debian 10, Windows 10]
- Client: [e.g. Nebulo, Unbound, Bind9, Dnscrypt-v2, Intra]
- Protocol: [e.g. DoH, DoT, Dnscrypt]

**Additional context**

**Comment by ookangzheng** [comment]
Pls check here: https://github.com/ookangzheng/blahdns/issues/183#issuecomment-853261374

I will try to build my own statuspage without paying to uptimerobot.

**Comment by obeho** [comment]
wdym @ookangzheng ?? I can see the free plan on their [page](https://uptimerobot.com/pricing/). Does that not work anymore?

If so, check out [this](https://hetrixtools.com/) alternative.


![upr](https://user-images.githubusercontent.com/71698631/128604379-64792204-f45e-42a1-a0e2-b9b5495cd19e.png)

**Comment by obeho** [comment]
This is really crucial because the past 2 days the resolution time has been increasing to several seconds per query, and several times completely not reachable (server drop-out or non-reachable). I'm on Finland DoH.

**Comment by ookangzheng** [comment]
@obeho @lolly223 
Pls check it out: https://hetrixtools.com/r/351d3d240b3e735972f76ca0943af50f/

**Comment by obeho** [comment]
Yes, thank you @ookangzheng. Something is better than nothing.

Though, I'm worried about the latencies. 

In the doh-jp server, see the average latencies from Tokyo server pings. On an average its around 200ms. Same city DNS resolution taking 200ms is a troublesome number.

In the doh-de server, average latencies from Frankfurt server which less than 100km from the Hetzner's Germany server, is more than 100ms.

Surprisingly, the Singapore server seems to have the best latencies.

**Comment by ookangzheng** [comment]
Can you provide MTR result for your network?

**Comment by obeho** [comment]
The latencies values above were taken from the new ping test [website](https://hetrixtools.com/r/351d3d240b3e735972f76ca0943af50f/)'s detailed reports. Its not something I have tested it.

Nevertheless, here are my [results](https://snippet.host/anqa).

**Comment by ookangzheng** [comment]
Which city or nearest country are you in?
Otherwise, please give DNSCrypt a try.

**Comment by obeho** [comment]
The latencies issue is not from my place. It is from the testing [server](https://hetrixtools.com/r/351d3d240b3e735972f76ca0943af50f/) place, which was recently setup by yourself.

Anyways, I did try to use DNSCrypt several times, but shifted back to doh due to an additional 100ms overhead in resolution.
