### ISSUE TITLE
🚀 can you add this ads and malicious domains??

### ISSUE THREAD

**Issue by loku0** [ookangzheng/blahdns#204]
[Balance protection domain.txt](https://github.com/ookangzheng/blahdns/files/6951852/Balance.protection.domain.txt)

**Comment by ookangzheng** [comment]
This list is huge.
Let me check which domain is not listed.

**Comment by ookangzheng** [comment]
Those address that you submit earlier is blocked, so don't worry 😄

**Comment by loku0** [comment]
> Those address that you submit earlier is blocked, so don't worry 😄oww thats nice sorry if you dont mind you deleted my pegasus post ??you have already added those links?? Thank you
