### ISSUE TITLE
 block ads tracker?

### ISSUE THREAD

**Issue by hunter5687346** [ookangzheng/blahdns#206]
do you block this ads trackers ?some apps showing ads
[ads trackers.txt](https://github.com/ookangzheng/blahdns/files/6968447/ads.trackers.txt)

**Comment by ookangzheng** [comment]
Those texts are not valid URLs. 
BlahDNS only blocked ads by domain name only.

**Comment by hunter5687346** [comment]
> Those texts are not valid URLs.
> BlahDNS only blocked ads by domain name only.

https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt do you blk this links?

**Comment by ookangzheng** [comment]
Yes
