### ISSUE TITLE
🤗Strange Resolving

### ISSUE THREAD

**Issue by minoplhy** [ookangzheng/blahdns#207]
This is just my Personal opinion . Although i can't confirm anything .

I Notice that some domain Says to be blocked by homepage still being resolved by DNS server in almost every country

"wes.df.telemetry.microsoft.com" All . Except Japan
"wer.alpha.telemetry.microsoft.com" All Excpet Japan
"watson7.alpha.telemetry.microsoft.com" All Except Japan
"watson2.alpha.telemetry.microsoft.com" All Except Japan
"watson.ppe.telemetry.microsoft.com" All Except Japan
"watson.df.telemetry.microsoft.com" All Excrpt Japan
"watson.alpha.telemetry.microsoft.com" All Except Japan
"vortex-win-sandbox.data.microsoft.com" All Except Japan
"vortex-sandbox.data.microsoft.com" All Except Japan
"fxos.telemetry.mozilla.org" All Except Japan
"df.telemetry.microsoft.com" All Except Japan

**Comment by ookangzheng** [comment]
Fixed. 
I tested something on Japan server but forgot to revert it.
