### ISSUE TITLE
Blacklist issue🐛 

### ISSUE THREAD

**Issue by obeho** [ookangzheng/blahdns#209]
The domains `zunsoach.com`, `freychang.fun`, `wonderhsjnsd.com`, `nkyouvery.fun` are present in Goodbyeads [list](https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt).

But all the above are shown as _not block_ and are successfully resolved. (using doh-sg server)

What's the issue here @ookangzheng? I keep finding (#194, #196) more and more domains that are present in one or more lists [here](https://github.com/ookangzheng/blahdns/blob/master/hosts/source.txt). But still those domains are not being blocked.

**Comment by ookangzheng** [comment]
Fixed

**Comment by obeho** [comment]
Ok, but what's happening? Asking because this seems to be a recurring issue. Not a one-off.

**Comment by ookangzheng** [comment]
It doesn't include in oisd block list, which block list are you referring to?

I was testing with some strange blocklist before and I forgot to revert them.

**Comment by obeho** [comment]
> The domains zunsoach.com, freychang.fun, wonderhsjnsd.com, nkyouvery.fun are present in Goodbyeads list.

https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt

All 5 are in this list.

If you were testing new blocklists, then more domains should be blocked, in addition to the existing ones in blocklists. Unless, you replaced the existing lists with new lists. Is that what happened?

**Comment by ookangzheng** [comment]
Already blocked. Please give it sometimes to grep the latest block list.
