### ISSUE TITLE
Request to block advertising on Android

### ISSUE THREAD

**Issue by Dadan59DK** [ookangzheng/blahdns#21]
Hello, 
 

Is it possible to block trackers ads on the following smartphones: admobservice, mopub, applovin? 
 

I use blokada on Android to block ads, but blah dns doesn't unfortunately block them, so I point it out to you, thanks 🙂

**Comment by ookangzheng** [comment]
Both of our blacklists are included Admobservie, Mopub, Applovin
Blacklist: [https://github.com/ookangzheng/blahdns/blob/master/hosts/rpz.blacklist?raw=true](https://github.com/ookangzheng/blahdns/blob/master/hosts/rpz.blacklist?raw=true)
On Android phone (OS version 9 below) I suggest you install Intra on google play. Use dns-over-https to connect.
