### ISSUE TITLE
🤗 Ask Authorisation for create mobileconfig file.

### ISSUE THREAD

**Issue by BirdInFire** [ookangzheng/blahdns#212]
Hello @ookangzheng ,

I actually had done some .mobileconfig Pull request on the [encrypted-dns](https://github.com/paulmillr/encrypted-dns) repository of [paullmir](https://github.com/paulmillr),
And I want to ask if you agree that I generate for your different server .mobileconfig profile for apple device in this repository.

Thanks for your answer

**Comment by ookangzheng** [comment]
@BirdInFire 
Yes please.

**Comment by BirdInFire** [comment]
@ookangzheng PR will be done ASAP thanks

**Comment by BirdInFire** [comment]
Sorry i push them now (my isp was targetted by ddos so i don't had the courage to do that during the calm), will do it during the week who come (or today if i have motivation evening) ^^

**Comment by BirdInFire** [comment]
@ookangzheng have done PR two day ago wait for their response close this issue

**Comment by BirdInFire** [comment]
@ookangzheng blahDNS is on their page (if you want to add it to source) : https://github.com/paulmillr/encrypted-dns
