### ISSUE TITLE
Blocklist Update 

### ISSUE THREAD

**Issue by leonicholasthe3** [ookangzheng/blahdns#218]
Hello Ed, I'm just using your BlahDNS and it works flawlessly. I just wonder is it the blocklist that inside the DNS already got update automatically?

nb: sorry for my newbie question and my english isn't good too

**Comment by ookangzheng** [comment]
It will auto update once a day.

**Comment by leonicholasthe3** [comment]
Thank you for the reply.. all right and first of all, I really like this DNS Service.

**Comment by leonicholasthe3** [comment]
Is there any error on the DNS, It seems I can't access any page because it's just show "This site can’t be reached... server IP address could not be found"

**Comment by ookangzheng** [comment]
Please check it here if DNS server has error.
https://stats.blahdns.com

**Comment by ookangzheng** [comment]
Should be okay now

**Comment by leonicholasthe3** [comment]
Unfortunately sir, I just sorry to say that the error still happened in DOT while I just testing JP server and any website got resolve. The error still happened 🙏

**Comment by ookangzheng** [comment]
Which protocol do you use?
DoT or DoH or DoQ or DNSCrypt

**Comment by leonicholasthe3** [comment]
DoT

**Comment by ookangzheng** [comment]
Still not working?

**Comment by leonicholasthe3** [comment]
Thanks again for your reply and it's already okay 🙏
