### ISSUE TITLE
🐛BlahDNS seems to block some parts of Google Maps functionality on Android

### ISSUE THREAD

**Issue by bige93** [ookangzheng/blahdns#222]
**Checklist**

- [X] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [X] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [X] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Looks like BlahDNS blocks some domains that are used in Google Maps.
Getting _Loading..._ when trying to get directions, load details of the place, etc.
Now switched to AdGuard DNS for a test and so far so good.

Google Pixel, doh-ch (and -de) server added as Private DNS in Settings.

Was working fine until one of the recent updates of G Maps app.

**To Reproduce**

1. Trying to route
2. Get Loading....
3. Disable Private DNS, toggle Airplane mode.
4. Trying again with success

**Expected behavior**
For app to work properly :)
**Logs (optional)**
Device is not rooted, so I don't believe I can provide much logs (never tried TBH😅)
**Client (if applicable):**

- Device: Google Pixel (sailfish) 
- OS: Android 11
- Client: Built-in Private DNS option
- Protocol: DoH

Thank you.

**Comment by ookangzheng** [comment]
Still not working?
@bige93

**Comment by bige93** [comment]
> Still not working?
> @bige93

Seems to be working fine now. I've been using DoH CDN on my temporary iPhone for around a week now - no issues. 
Just checked on Pixel with DoH-DE - maps work as expected. 
Thank you!

**Comment by ookangzheng** [comment]
Thanks for your feedback.
