### ISSUE TITLE
BlahDNS adsblock list cant access to website with dot com

### ISSUE THREAD

**Issue by nkoc6a15** [ookangzheng/blahdns#227]
**Checklist**

-  [.] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [.] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [.] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Cant access the .com websites because in your filterlist have ||com^^ rule. Can you remove it? Im using Ublock Origin with Firefox 94

**Comment by ookangzheng** [comment]
Fixed, pls try it again

**Comment by nkoc6a15** [comment]
Its now fixed, this issue can be closed. Thank you very much
