### ISSUE TITLE
🐛 blahdns seems to block some dyndns addresses

### ISSUE THREAD

**Issue by averon420** [ookangzheng/blahdns#228]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Blahdns seems to block entries of https://www.dynu.com/ a dyndns service.

**To Reproduce**

1. Create a dyndns entry on https://www.dynu.com/
2. Setup blahdns on mobile phone
3. Try to resolve your dnsdns address

**Expected behavior**
To resolve it normaly

**Logs (optional)**
-

**Additional context**
Like the service, still testing arround.

**Comment by ookangzheng** [comment]
<img width="904" alt="Screen Shot 2021-11-06 at 07 25 33" src="https://user-images.githubusercontent.com/6301735/140588795-da42227b-4244-452e-bac8-1468e4c27335.png">

Pls try again.

**Comment by averon420** [comment]
hi there, the domain I use is *.mywire.org and its still blocked. thanks for your quick help :)

**Comment by ookangzheng** [comment]
Should be fixed now

**Comment by averon420** [comment]
works! thanks a lot very much appreciated
