### ISSUE TITLE
🐛 photos.google.com and manga-news.com to whitelist

### ISSUE THREAD

**Issue by lgianina** [ookangzheng/blahdns#229]
Hi and thank you for making BlahDNS !

I have noticed that some safe domains are unreachable when BlahDNS is used.
These issues does not happen when using another DNS provider which doesn't use filters.

**[manga-news.com](https://manga-news.com/)**

This is a popular and safe news site about Japanese culture for french-speaking peoples.
He is absolutely not dangerous nor malicious. I guess it is a false positive.

**[https://photos.google.com/](https://photos.google.com/)**

For example, here, pictures previews are blurry and when I open a picture, the top-right actions (Zoom, Details etc...) doesn't work:
[https://photos.google.com/share/AF1QipMbCeKvBffjNpwMQE9Yl4owAb-jfKAgDRYJPYwedtteZbHJtfMf2G5NxHTLkumH8Q?key=UzlRLXVZNWdhTENUMG4yTzhIcTk0TFpWUndFXy13](https://photos.google.com/share/AF1QipMbCeKvBffjNpwMQE9Yl4owAb-jfKAgDRYJPYwedtteZbHJtfMf2G5NxHTLkumH8Q?key=UzlRLXVZNWdhTENUMG4yTzhIcTk0TFpWUndFXy13)

Plus, some other albums aren't displayed at all:
[https://photos.google.com/share/AF1QipMDZIOVTH3His16bVQ0oKX598JfQhCH5oME8zkZDN11ruuZBAU24dH5-OwsNn8HsQ?key=aExzMmFab1RHZXB2bF9hWk80bm5XUV9ITlJ4S3R3](https://photos.google.com/share/AF1QipMDZIOVTH3His16bVQ0oKX598JfQhCH5oME8zkZDN11ruuZBAU24dH5-OwsNn8HsQ?key=aExzMmFab1RHZXB2bF9hWk80bm5XUV9ITlJ4S3R3)

Many thanks in advance to unblock these domains and thanks again for your work on this DNS service.

**Comment by ookangzheng** [comment]
Google Photos all functionalities that you mentioned above is working for me.

Fixed `mange-news.com`

**Comment by lgianina** [comment]
Sorry, Google Photos issues was due to the LocalCDN add-on installed on my Firefox.

But `manga-news.com` doesn't seems to work:

![snip_00001](https://user-images.githubusercontent.com/91754578/140638257-73495e3b-626d-4cd6-bcf4-f8876484c5b2.png)
![snip_00002](https://user-images.githubusercontent.com/91754578/140638260-a87e939a-89ed-4e47-894a-c73fd1d44c99.png)

**Comment by ookangzheng** [comment]
<img width="644" alt="Screen Shot 2021-11-08 at 10 46 06" src="https://user-images.githubusercontent.com/6301735/140676297-2b71cb77-a95a-4b05-a263-7ff28d449f6b.png">
Found in oisd.nl basic list

**Comment by lgianina** [comment]
The site now works as expected, thank you !
