### ISSUE TITLE
🐛 tv.scdn.co block prevents Spotify to play on TV

### ISSUE THREAD

**Issue by mmwvh** [ookangzheng/blahdns#230]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
tv.scdn.co is blocked and it prevents Spotify to play on TV, can it be unblocked?

**Comment by ookangzheng** [comment]
Fixed
