### ISSUE TITLE
🐛 Albums aren't display on imgur.com

### ISSUE THREAD

**Issue by lgianina** [ookangzheng/blahdns#232]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
On [imgur.com](https://imgur.com/), some albums aren't display, there's only a plain gray page instead of the content.

**To Reproduce**
Go on these pages, for example:

https://imgur.com/a/lyuQJHU
https://imgur.com/a/FKEWXjU
https://imgur.com/a/X7AU61Q

Here's what these pages looks like with BlahDNS enabled:

![b](https://user-images.githubusercontent.com/91754578/141352962-dc3a418f-23d8-4b29-a792-feda2826f90f.png)

**Expected behavior**
Pages should looks like this:

![a](https://user-images.githubusercontent.com/91754578/141353008-cd5317c8-399d-4e4a-a0aa-9e15344036fe.png)

**Client (if applicable):**

- Device: Windows computer and Android phone
- OS: Windows 10 and Android
- Browser: Latest Firefox stable release on PC and latest Firefox beta version on Android
- Protocol: DoH in Firefox

I suspect a false positive from the whole imgur.com domain or parts of the site.

**Comment by ookangzheng** [comment]
Need whitelist `js.media-lab.ai` and problem should be fix

**Comment by lgianina** [comment]
Thank you, it works as expected !
