### ISSUE TITLE
🐛 query1.finance.yahoo.com & query2.finance.yahoo.com is blocked

### ISSUE THREAD

**Issue by Xathros1** [ookangzheng/blahdns#233]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Blahdns blocks those 2 query sites that are needed to fetch Yahoo finance API info.

**To Reproduce**
 Example URLs:
1. https://query1.finance.yahoo.com/v10/finance/quoteSummary/AAPL?modules=assetProfile%2CearningsHistory
2. https://query2.finance.yahoo.com/v10/finance/quoteSummary/NVDA?modules=incomeStatementHistoryQuarterly

**Expected behavior**
the query should succeed

**Client (if applicable):**

- Device: [Linux]
- OS: [Opensuse Tumbleweed]
- Client: [AVM Fritzbox 7590]
- Protocol: [DoT]

**Additional context**
-

**Comment by ookangzheng** [comment]
Fixed
