### ISSUE TITLE
🐛 Japan DNSCrypt returns incorrect signature

### ISSUE THREAD

**Issue by msoxzw** [ookangzheng/blahdns#234]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Japan DNSCrypt returns incorrect signature, but the [status page of Japan DNSCrypt](https://hetrixtools.com/report/uptime/286ca630f54ee841cdf68638ebd9dfbe/) shows it is operational.

**To Reproduce**
My test configuration file:  [dnscrypt-proxy-2.txt](https://github.com/ookangzheng/blahdns/files/7576352/dnscrypt-proxy-2.txt)

My test code: `dnscrypt-proxy -config dnscrypt-proxy-2.txt`

**Expected behavior**
Japan DNSCrypt returns correct certificate, and [status page of Japan DNSCrypt](https://hetrixtools.com/report/uptime/286ca630f54ee841cdf68638ebd9dfbe/) reflects the real condition of Japan DNSCrypt.

**Logs (optional)**
`[WARNING] [blahdns-jp-dnscrypt-v4] Incorrect signature for provider name: [2.dnscrypt-cert.blahdns.com.]`

**Server if applicable):**

- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. Vultr, AWS, OpenWRT, RaspberryPI]

**Client (if applicable):**

- Device: Windows
- OS: Windows 10
- Client: Dnscrypt-v2
- Protocol: Dnscrypt

**Additional context**

**Comment by ookangzheng** [comment]
Please try 
```
[static.'blahdns-jp-doh']
stamp = 'sdns://AgMAAAAAAAAADjEzOS4xNjIuMTEyLjQ3ABJkb2gtanAuYmxhaGRucy5jb20KL2Rucy1xdWVyeQ'
[static.'blahdns-jp-doh-v6']
stamp = 'sdns://AgMAAAAAAAAAIFsyNDAwOjg5MDI6OmYwM2M6OTJmZjpmZTI3OjM0NGJdABJkb2gtanAuYmxhaGRucy5jb20KL2Rucy1xdWVyeQ'
```

**Comment by msoxzw** [comment]
> Please try
> 
> ```
> [static.'blahdns-jp-doh']
> stamp = 'sdns://AgMAAAAAAAAADjEzOS4xNjIuMTEyLjQ3ABJkb2gtanAuYmxhaGRucy5jb20KL2Rucy1xdWVyeQ'
> [static.'blahdns-jp-doh-v6']
> stamp = 'sdns://AgMAAAAAAAAAIFsyNDAwOjg5MDI6OmYwM2M6OTJmZjpmZTI3OjM0NGJdABJkb2gtanAuYmxhaGRucy5jb20KL2Rucy1xdWVyeQ'
> ```

The `blahdns-jp-doh` indeed works, but it is not the case for the `blahdns-jp-dnscrypt`.

**Comment by ookangzheng** [comment]
Pls try this 
```
-blahdns systemd[1]: Started Dnscrypt server.
Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] State file [encrypted-dns.state] found; using existing provider key
Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] Public server address: 139.162.112.47:8443
Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] Provider public key: 2c2033d8f17354d4585e11c0db48837603defd843cc315c36d57232ae8846f4e
Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] Provider name: 2.dnscrypt-cert.blahdns.com
Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] DNS Stamp: sdns://AQMAAAAAAAAAEzEzOS4xNjIuMTEyLjQ3Ojg0NDMgLCAz2PFzVNRYXhHA20iDdgPe_YQ8wxXDbVcjKuiEb04bMi5kbnNjcnlwdC1jZXJ0LmJsYWhkbnMuY29t
Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] Public server address: [2400:8902::f03c:92ff:fe27:344b]:8443
Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] Provider public key: 2c2033d8f17354d4585e11c0db48837603defd843cc315c36d57232ae8846f4e
Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] Provider name: 2.dnscrypt-cert.blahdns.com
Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] DNS Stamp: sdns://AQMAAAAAAAAAJVsyNDAwOjg5MDI6OmYwM2M6OTJmZjpmZTI3OjM0NGJdOjg0NDMgLCAz2PFzVNRYXhHA20iDdgPe_YQ8wxXDbVcjKuiEb04bMi5kbnNjcnlwdC1jZXJ0LmJsYWhkbnMuY29t
```

**Comment by msoxzw** [comment]
> Pls try this, those detail are `DNSCrypt v2`
> 
> ```
> -blahdns systemd[1]: Started Dnscrypt server.
> Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] State file [encrypted-dns.state] found; using existing provider key
> Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] Public server address: 139.162.112.47:8443
> Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] Provider public key: 2c2033d8f17354d4585e11c0db48837603defd843cc315c36d57232ae8846f4e
> Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] Provider name: 2.dnscrypt-cert.blahdns.com
> Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] DNS Stamp: sdns://AQMAAAAAAAAAEzEzOS4xNjIuMTEyLjQ3Ojg0NDMgLCAz2PFzVNRYXhHA20iDdgPe_YQ8wxXDbVcjKuiEb04bMi5kbnNjcnlwdC1jZXJ0LmJsYWhkbnMuY29t
> Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] Public server address: [2400:8902::f03c:92ff:fe27:344b]:8443
> Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] Provider public key: 2c2033d8f17354d4585e11c0db48837603defd843cc315c36d57232ae8846f4e
> Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] Provider name: 2.dnscrypt-cert.blahdns.com
> Nov 22 02:34:57 jp1-debian-blahdns encrypted-dns[13762]: [INFO ] DNS Stamp: sdns://AQMAAAAAAAAAJVsyNDAwOjg5MDI6OmYwM2M6OTJmZjpmZTI3OjM0NGJdOjg0NDMgLCAz2PFzVNRYXhHA20iDdgPe_YQ8wxXDbVcjKuiEb04bMi5kbnNjcnlwdC1jZXJ0LmJsYWhkbnMuY29t
> ```

I appreciate your prompt resolution, and both plain DNSCrypt and anonymized DNSCrypt function well. Unfortunately, I do not have IPv6 Internet environment to verify the result of DNSCrypt with IPv6 address.

**Comment by ookangzheng** [comment]
Okay, hope this fix your problem.
