### ISSUE TITLE
Podcast sources blocked🐛 

### ISSUE THREAD

**Issue by JosefEreq** [ookangzheng/blahdns#237]
**Describe the issue**
Many podcast sources get blocked. This happens on mulitple plattforms(Acast, Apple Podcast, TuneIn) and any device type i tested using blahDNS for lookup.
Some sources work but the big majority of mine gets blocked, for example Stuff You Should Know.

**To Reproduce**

1. Fetch podcast.
2. Podcast times out.

**Expected behavior**
Podcast should be resolved and downloaded.

**Client (if applicable):**

- Device: iPhone, MacOS
- OS: iOS 15.2, MacOS 12.0.1
- Client: DNSCloak iOS, dnscrypt-proxy macOS. 
- Protocol: Dnscrypt

**Comment by ookangzheng** [comment]
Fixed 
whitelist: `traffic.megaphone.fm`
