### ISSUE TITLE
🚀 Unblock  Ethermine/Bitfly related sites

### ISSUE THREAD

**Issue by Sn0whax** [ookangzheng/blahdns#240]
**Is your feature request related to a problem?**
Ethermine (Ethereum) currently works but some of the other related sites are currently blocked.
Ethermine and its respective sites are legitimate and A tier mining pools.

**Describe the solution you'd like**
Please unblock the following:
ergo.flypool.org
ethpool.org
zcash.flypool.org
etc.ethermine.org
beam.flypool.org
ravencoin.flypool.org

Pool Servers:
eu1-zcash.flypool.org 
us1-zcash.flypool.org 
asia1-zcash.flypool.org 
asia1-etc.ethermine.org 
eu1-etc.ethermine.org 
us1-etc.ethermine.org 
eu1-beam.flypool.org 
us1-beam.flypool.org
asia1-beam.flypool.org 
stratum-ravencoin.flypool.org
stratum-ergo.flypool.org 

Love BlahDNS, keep up the great work!

**Comment by ookangzheng** [comment]
Done
