### ISSUE TITLE
🚀 flexpool.io API is blocked (api.flexpool.io)

### ISSUE THREAD

**Issue by Sn0whax** [ookangzheng/blahdns#241]
**Is your feature request related to a problem?**
Flexpool and it's corresponding servers are unblocked but the API is not. This is a request to unblock the API server which allows clients to check the statistics - api.flexpool.io

**Describe the solution you'd like**
Request to unblock: 
api.flexpool.io

Thanks so much, yet again!

**Comment by ookangzheng** [comment]
Done
