### ISSUE TITLE
🚀 Possible upgrade from "https://abp.oisd.nl/basic/" to "https://abp.oisd.nl/"

### ISSUE THREAD

**Issue by Sn0whax** [ookangzheng/blahdns#242]
**Is your feature request related to a problem?**
Changing the source on OISD from "https://abp.oisd.nl/basic/" to "https://abp.oisd.nl/" would allow for much stronger tracking protection. This increases the size from 586kb to 6.3MB.

**Describe the solution you'd like**
Replace "https://abp.oisd.nl/basic/" with "https://abp.oisd.nl/". Risks involve false positives that i believe we may sort out with whitelists over time.

Thanks again!

**Comment by ookangzheng** [comment]
I wouldn't take it into consider about replacing basic to full osid list.
I've confidence that so far the blocklist that I use is efficient enough.
