### ISSUE TITLE
🐛 Podcast stream not resolved

### ISSUE THREAD

**Issue by JosefEreq** [ookangzheng/blahdns#248]
Describe the issue
Stuff you should know podcast started getting blocked again. This happens on mulitple plattforms(Acast, Apple Podcast, TuneIn) and any device type i tested using blahDNS for lookup.

To Reproduce

    Fetch podcast.
    Podcast times out.

Expected behavior
Podcast should be resolved and downloaded.

Client (if applicable):

    Device: iPhone, MacOS
    OS: iOS, MacOS
    Client: DNSCloak iOS, dnscrypt-proxy macOS.
    Protocol: Dnscrypt

**Comment by ookangzheng** [comment]
Hi,

May I know with Podcast app do you use?

**Comment by JosefEreq** [comment]
I've tried Apple Podcast and Acast.

**Comment by ookangzheng** [comment]
Hi,

problem solved?  Or still exist?
If so, please paste the DNS resolution log here for diagnostic purpose.

Thanks

**Comment by JosefEreq** [comment]
Problem solved, thanks!
