### ISSUE TITLE
🐛 Cert expired on Singapore server

### ISSUE THREAD

**Issue by berrabe** [ookangzheng/blahdns#253]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
We have cert expired on singapore server, please re-new the cert

**To Reproduce**
Just query to singapore server using kdig / dog with DoT / DoH protocol

**Logs (optional)**
![image](https://user-images.githubusercontent.com/34432326/168933097-32ebe697-5819-4afc-9f57-1a2c33633d5d.png)

**Comment by ookangzheng** [comment]
Fixed
