### ISSUE TITLE
🤗 How to use BlahDNS on iOS

### ISSUE THREAD

**Issue by marcocce** [ookangzheng/blahdns#255]
Hi, first of all congratulations for the great work you put behind it to create this and I am highly grateful. 
I wanted to ask you which server you recommend to use on iOS.
I saw that this [site](https://encrypted-dns.party/) recommended by so many people offers various DNS that can be used with iPhones. 
What does the CDN acronym that is in the BlahDNS section mean and what is the difference of it with those below referring to each server. I don't know if I have made myself understood. Thank you very much again for everything!

Kind regards :)

**Comment by ookangzheng** [comment]
According to the site you mentioned above, it uses a fake VPN profile to redirect your iOS DNS resolution packet to up stream selected DNS provider.

And CDN acronym means it only can be use with DNS-over-HTTPS. If you are live far from Japan, Singapore, Switzerland, Germany or Finland. The first time connection will be slow, so CDN may come to help you with. Other than that, it is just the same as direct connect to BlahDNS various servers.

**Comment by marcocce** [comment]
Thank you very much for the excellent explanation!
