### ISSUE TITLE
🤗 Unblock geojs.io

### ISSUE THREAD

**Issue by averon420** [ookangzheng/blahdns#260]
Hello, could you please unblock **geojs.io** I need it for geoblocking plugin via traefik.

**Comment by ookangzheng** [comment]
Done

**Comment by averon420** [comment]
Hello, thanks, but the subdomain "get.geojs.io" is still blocked. Could you also fix that? 
Thanks

**Comment by ookangzheng** [comment]
Sorry, it should be fix

**Comment by averon420** [comment]
Thanks a lot :)
