### ISSUE TITLE
🐛 [Whitelist] Pixlr.com online editors does not work

### ISSUE THREAD

**Issue by lgianina** [ookangzheng/blahdns#262]
Hi and thank you for your work on this DNS provider !

It seems Pixlr online editors does not work at all with BlahDNS enabled in Firefox on PC with both uBlock Origin and Tracking Protection totally disabled.

Here are the links to the editors :

[https://pixlr.com/e/](https://pixlr.com/e/)
[https://pixlr.com/x/](https://pixlr.com/x/)

To reproduce the issue, try to **OPEN IMAGE** with the blue button or to navigate in the left-side pane menus.

No prompt open at all to open an image and no menus are displayed, the service is basically a static page and nothing work as expected.

It may be caused by some false-positive domains used on Pixlr that needs to be whitelisted.

Many thanks in advance !

**Comment by ookangzheng** [comment]
It works for me, and domain is resolved correctly.
Please try again.

Thanks
