### ISSUE TITLE
It seems that dnscrypt-jp v4 doesn't work.

### ISSUE THREAD

**Issue by yutayu** [ookangzheng/blahdns#269]
sdns://AQMAAAAAAAAAEzEzOS4xNjIuMTEyLjQ3Ojg0NDMghROpa8Tgg0uVDWO1AujT4tVNBJZrJgKTNOkHHboj_CsbMi5kbnNjcnlwdC1jZXJ0LmJsYWhkbnMuY29t

no response.

**Comment by yutayu** [comment]
sorry , I wil check whether dnscrypt-proxy problem.

**Comment by yutayu** [comment]
When I use your dnscrypt-proxy conf file , It works.
Very sorry.

**Comment by yutayu** [comment]
It doesn't work ,now.

**Comment by ookangzheng** [comment]
Still not working?

**Comment by yutayu** [comment]
Sorry for no response.
It works now.
I will check while.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by yutayu** [comment]
and now it stops lol.

**Comment by ookangzheng** [comment]
still?

**Comment by yutayu** [comment]
It works now , I will check again.

Proton Mail モバイルから送信

---元のメッセージ---
2022年9月1日 12:02 に ookangzheng が送信:

**Comment by yutayu** [comment]
It seems that it stops sending query sometimes.

**Comment by yutayu** [comment]
I use dot now.
