### ISSUE TITLE
🐛 Domain tag.aticdn.net is blocked

### ISSUE THREAD

**Issue by mmwvh** [ookangzheng/blahdns#271]
**Checklist**

- [x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
'tag.aticdn.net' seemed to be blocked and it breaks the streaming service of the Dutch national broadcaster. Could you allow this domain?

**Comment by ookangzheng** [comment]
Fixed
