### ISSUE TITLE
🐛 Whitelist : upi.npci.org.in

### ISSUE THREAD

**Issue by Github-contribute** [ookangzheng/blahdns#272]
**Checklist**

- [ Yes ] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [ Yes ] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [ Yes ] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Pls Whitelist ( upi.npci.org.in ) blahdns break this host so, the app is break.

**Comment by ookangzheng** [comment]
Done
