### ISSUE TITLE
🚀 Suggestions for Good Hosts

### ISSUE THREAD

**Issue by Github-contribute** [ookangzheng/blahdns#273]
**Is your feature request related to a problem?**
Yes

**Describe the solution you'd like**
Suggestion for Good host for blocking ads , trackers and malware.

**Describe alternatives you've considered**
1. Oisd Full
2. 1host Pro
3. GoodbyeAds
4. StevenBlack

**Additional context**
I want to know which hosts are using in blahdns?

**Comment by ookangzheng** [comment]
Hi,

Those blocklist are already included

**Comment by Github-contribute** [comment]
I thought blah using only oisd full host, others 3 I figure out not that's y iam asking. I can u which hosts are using in blah?

**Comment by ookangzheng** [comment]
Here 
https://github.com/ookangzheng/blahdns/blob/master/hosts/source.txt
