### ISSUE TITLE
Japan and Singapore still have the old IP address written on blahdns.com (please update).

### ISSUE THREAD

**Issue by ghost** [ookangzheng/blahdns#278]
### Japan
![Japan](https://user-images.githubusercontent.com/117177126/206830303-84318b3b-adf7-4130-9a94-abcd63573418.png)

### Singapore
![Singapore](https://user-images.githubusercontent.com/117177126/206830316-95914373-62b3-4a28-96e4-40a5208c2f5a.png)

### New IP address as written [here](https://github.com/ookangzheng/blahdns/tree/master/server-conf)
![nslookup](https://user-images.githubusercontent.com/117177126/206830327-c4aaf2c5-9af2-45c8-a62b-559cb3e5edd4.png)

**Comment by ookangzheng** [comment]
Done
