### ISSUE TITLE
dot-de is down again.🐛 

### ISSUE THREAD

**Issue by daemonserj** [ookangzheng/blahdns#279]
subj.

 kdig -d @dot-de.blahdns.com +tls-ca +tls-host=dot-de.blahdns.com example.com
;; DEBUG: Querying for owner(example.com.), class(1), type(1), server(dot-de.blahdns.com), port(853), protocol(TCP)
;; DEBUG: TLS, imported 129 system certificates
;; WARNING: connection timeout for 2a01:4f8:c17:ec67::1@853(TCP)
;; WARNING: connection timeout for 78.46.244.143@853(TCP)
;; ERROR: failed to query server dot-de.blahdns.com@853(TCP)

**Comment by ookangzheng** [comment]
Hi，

Should be fixed now
