### ISSUE TITLE
🐛Mistake on the Japan DoT link

### ISSUE THREAD

**Issue by Dyras** [ookangzheng/blahdns#280]
**Checklist**

- [X] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [X] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [X] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
To keep it short, look at these pictures:
Japan:
![image](https://user-images.githubusercontent.com/12563436/223411088-d42742ce-7c2a-440a-af3f-194b4ee7989a.png)
Switzerland:
![image](https://user-images.githubusercontent.com/12563436/223411182-472a1604-6842-4d6a-ac1b-8129c7b19b2f.png)

**To Reproduce**

1. Go on the website
2. Scroll down to Switzerland. Look at DNS-over-TLS, and how the tls_auth_name is above the DoT link
3. Go down a bit more to Japan. Notice how tls_auth_name is right next to the DoT link

**Expected behavior**
tls_auth_name should be above DoT on the Japan server, not next to it. This is the case with every server except Japan

**Additional context**
I tried to fix this in the index.html but it doesn't seem like the source code is up to date anymore? I wanted to fix some spelling errors etc as well and half of the sentences on the website aren't in the source code.

**Comment by ookangzheng** [comment]
Hi @Dyras , 

Thanks for your contribution. 
I will update the latest website html source code and send me a pull request.

Thanks
