### ISSUE TITLE
new form of ads

### ISSUE THREAD

**Issue by idnovic** [ookangzheng/blahdns#32]
I found this article, please take a look and block the ads. Thank you!

hXXps://www.buzzfeednews.com/article/craigsilverman/in-banner-video-ad-fraud

**Comment by idnovic** [comment]
one url is 

play.aniview.com

here is a video where you can see the problem:
hXXps://m.youtube.com/watch?feature=player_embedded&v=59jK66Ut8tY

**Comment by idnovic** [comment]
an other is

ssp.lkgd.net

**Comment by ookangzheng** [comment]
Please provide a site or example and note them out.
Please try it our self on the terminal is the domain still exist, then put it inside the issue.
Thanks.

**Comment by ookangzheng** [comment]
Try and see, most of those url already added into blacklist.
