### ISSUE TITLE
add another whitelist

### ISSUE THREAD

**Issue by idnovic** [ookangzheng/blahdns#33]
Can you add the whitelisted domains here?

https://github.com/anudeepND/whitelist

**Comment by idnovic** [comment]
the lists are here:
https://github.com/anudeepND/whitelist/tree/master/domains

**Comment by ookangzheng** [comment]
Hi, I know this. but I won't include all of this whitelist.
What website you can't surf?

**Comment by arkadi0** [comment]
Hello ookangzheng. Please consider adding following sites to whitelist:
forsal.pl
money.pl
growlrservice.initechapps.com

**Comment by idnovic** [comment]
please unblock

https://mydealz.digidip.net/
