### ISSUE TITLE
SZ blocked URL

### ISSUE THREAD

**Issue by muibusan** [ookangzheng/blahdns#35]
I cannot access the following domain in my browser using BlahDNS, it says page not found:
https://immobilienmarkt.sueddeutsche.de/cms/immobilienmarkt/immobilien-anbieten/produkte-und-preise/privatkunden/mietmarkt/online

Without BlahDNS it works fine.

I use Firefox 66 x64, network.trr.mode set to "3" (=force DNS over HTTPS).

**Comment by ookangzheng** [comment]
Done
