### ISSUE TITLE
Latest Announcement**

### ISSUE THREAD

**Issue by ookangzheng** [ookangzheng/blahdns#36]
**SSL Certificate date**

- Japan SSL cert will be expired on `Monday, July 20, 2020`
- Germany SSL cert will be expired on `Monday, July 20, 2020`
- Finland SSL cert will be expired on `Monday, July 20, 2020`
- Singapore SSL cert will be expired on `Sunday, July 19, 2020`

### April
1. Add Singapore server BETA. Support DoH (`dns-query` and `uncensor`), DoT.

### March
1. Add DoH path with `dns-query` as filtered, `uncensor` without filtered.
2. Google Analytics tracking script url:`www.google-analytics.com` is blocked, but Admin panel for site admin not block:  `analytics.google.com` (2020-03-04 17:12 GMT+8)

### Feb
1. Dropped connection from China due to DDos attack recently, China user pls use `doh1.blahdns.com` and `doh2.blahdns.com` instead. 

---

## Year 2019
**Nov**
1. Switzerland server is shutdown
2. Finland server is up and running

**September**
1. Japan IPv6, not reachable has been fixed. (Sep, 15)
2. Switzerland IPv6 down for 3 minutes. ( Sep, 18) 
3. Germany DNS server currently having IPv6 problem, pls be patient.--- FIXED (09-21, 16:31 GMT+8) 

**July**
1. Fixed Intra DoH getting some error, miss blocked `dns.google.com` domain cause this error message ( Fix on July 3, 2019)

**April**
1. Germany server has been reinstall and uses the new solution to provide better and faster service, enjoy (April 16, 2019)

## Future plan
1. Mumbai server
2. Brazil server
3. Singapore Server
---
### Expired
* Japan DoH, DoT address has been migrated to
  - DoH: doh-jp.blahdns.com
  - DoT: dot-jp.blahdns.com
(old domain doh.blahdns.com & dns.jp.blahdns.com will shut down on March 31, 2019)
* Japan Ipv6 problem fixed. 2019-02-17 (Vps provider suddenly added an IPv6, so I have 2 IPv6. But the knot-resolver was set to listen `[::]` automatically. I manually listen both of them, everything works fine again. Sorry for the inconvenient.
* Server in Germany currently highly unstable, I will try to fix it ASAP. Thanks (Problem solved, still have to monitor it) 
* IMPORTANT - PORT 53 will shut down soon, be sure you use DoT, DoH, DNSCryptv2.
* Old Germany server IP 217.61.0.97 will shutdown at October 30 2018
* Blahdns Germany Server Migration announcement, Start: October 28, 2018, 8:00:00 AM CEST, follow this [issue](https://github.com/ookangzheng/blahdns/issues/5)

**Comment by yutayu** [comment]
At least , doh-jp dnscrypt-jp are down

**Comment by ookangzheng** [comment]
Pls open new issue.
Thanks

**Comment by yutayu** [comment]
excuse me.
