### ISSUE TITLE
Request for white list for the following websites

### ISSUE THREAD

**Issue by Dadan59DK** [ookangzheng/blahdns#37]
Hello, 

can you put these links on a white list, because I'm a pain in the ass to work! 

Thank you.

https://www.dealabs.com
https://developer.spotify.com/web-api/
https://ginjfo.com
http://www.serialsws.org
https://fr-fr.facebook.com
https://best.aliexpress.com
https://fr.yahoo.com
https://www.ask.com
https://r.orange.fr/r/OGwebmail_inbox

**Comment by ookangzheng** [comment]
www.dealabs.com not blocked
https://developer.spotify.com/web-api/ not blocked 
https://ginjfo.com/ not blocked 
http://www.serialsws.org/ not blocked
https://fr-fr.facebook.com/ not blocked
https://best.aliexpress.com/ not blocked 
fr.yahoo.com not blocked 
www.ask.com fixed
r.orange.fr fixed

**Comment by Dadan59DK** [comment]
There must be a problem with your dns, with me in France everything is blocked, when I test with Google dns, everything works perfectly well!
