### ISSUE TITLE
minisign key?

### ISSUE THREAD

**Issue by volia2** [ookangzheng/blahdns#39]
Hi,

I'm sorry if I miss it, but I can't see it in the site and wiki.
Can you please tell me the minisign key for this DNS? because dnscrypt2 needs to have the key to verify the url.

Thanks!

**Comment by ookangzheng** [comment]
Do you mean this?
https://github.com/DNSCrypt/dnscrypt-resolvers

**Comment by volia2** [comment]
Yes, if you look at the .md files, they'd have minisign_key, and you need to have that to install the dns to dnscrypt.
![Annotation 2019-06-25 192007](https://user-images.githubusercontent.com/10745233/60097759-4624c880-977e-11e9-9c56-612836d0c346.jpg)

**Comment by ookangzheng** [comment]
I would suggest use `[static]` method into your dnscryptv2
Check it here: https://github.com/ookangzheng/blahdns/blob/master/client-conf/dnscrypt/dnscrypt-proxy.toml#L26

**Comment by volia2** [comment]
Ahh, it works. Thanks, man.
