### ISSUE TITLE
Need add domain

### ISSUE THREAD

**Issue by luxysiv** [ookangzheng/blahdns#40]
Please add those domains:
ocsp.apple.com
app-measurement.com
ng-vn-notice.gameitop.com

**Comment by ookangzheng** [comment]
What do you mean? Blacklist or whitelist?
app-measurement.com has to be whitelist, it will break Google map

**Comment by luxysiv** [comment]
Blacklist. App measure I block but google map still works fine

**Comment by ookangzheng** [comment]
I tested app-measurement.com will break google service and firebase related SDK 
ocsp.apple.com will use by Apple certificate validation
Blacked list: ng-vn-notice.gameitop.com

**Comment by lightswitch05** [comment]
I can't believe `app-measurement.com` is needed. This is a major tracking service and should not be whitelisted
