### ISSUE TITLE
"You are not using Blahdns !" But I am! 

### ISSUE THREAD

**Issue by yilmzfurkan** [ookangzheng/blahdns#42]
Status page shows everything is working but I assume there is something wrong. I was using blahdns and just checked from the website it tells me "You are not using Blahdns !" I checked my DNS with other services and shows that I use blahdns.

**Comment by ookangzheng** [comment]
hmm sounds interesting. Idk what you encountered. Can you please share a screenshot with the Console tab. Chrome press Cmd+Shift+C
If everything works well, you will see this 
![image](https://user-images.githubusercontent.com/6301735/61431022-9c8cbd80-a95e-11e9-9231-35d23d92cfc6.png)

**Comment by yilmzfurkan** [comment]
It happens when my WireGuard is turned ON. Here is it without my WireGuard: https://files.catbox.moe/ym7aol.png

And here are the results when my WireGuard is turned ON:
https://files.catbox.moe/8zumdw.png

Even blahdns.com tells I don't use blahdns. dnsleaktest.com reports that I am using blahdns: https://files.catbox.moe/ydluto.png

**Comment by ookangzheng** [comment]
Hmm, I'm using Wireguard with my DNS as well.
I tested on Chrome and Firefox both work well, what happened 😢

**Comment by yilmzfurkan** [comment]
@ookangzheng I noticed that when I use Icecat it shows that I use blahdns. But weird behavior on Firefox. I use network.trr.mode 2 but even it fall-backs to system it should resolve blahdns. When I set it to network.trr.mode 3 it forces it but I don't know why on 2 it doesn't work. :thinking:

**Comment by ookangzheng** [comment]
I tried on Firefox with DoH and Wireguard both works

**Comment by yilmzfurkan** [comment]
@ookangzheng Firefox 68.0?

**Comment by ookangzheng** [comment]
Firefox 69 Developer Edition

**Comment by yilmzfurkan** [comment]
@ookangzheng tested on clean Firefox 68.0 profile and Firefox Nightly still the same. :thinking:

**Comment by ookangzheng** [comment]
No idea, sorry.

**Comment by Mikaela** [comment]
I don't know if this comment is of any use, but I see the same notice on Android 9 Go Edition (Nokia 1) that has been configured to use `dot-de.blahdns.com` as Private DNS when using Firefox Lite (that has no support for TRR/DoH that I know of).

Using Intra (`https://doh-de.blahdns.com/dns-query`) on another phone (Android 7.x) I see that I am using BlahDNS.

**Comment by ookangzheng** [comment]
Maybe the test has run though the timeout section

**Comment by ookangzheng** [comment]
@yilmzfurkan  I already increase the timeout and renewed HTTPS for `test.blahdns.com`, pls try again.

**Comment by yilmzfurkan** [comment]
@ookangzheng fixed, thanks.

**Comment by kevinfeber** [comment]
I am also facing the same problem i.e. how to enable blahdns on windows.
second question is what is blahdns address ?

Thank you.
