### ISSUE TITLE
Mi Home app blocked

### ISSUE THREAD

**Issue by PatPatShum** [ookangzheng/blahdns#43]
Hi, love your DNS but just 1 issue stopping me from using it. I use a lot of Xiaomi smart home devices and with your DNS on, my Mi Home app on Android can't connect to my home devices. Not sure if the connection to the Xiaomi servers are blocked?

**Comment by ookangzheng** [comment]
I dont have MI home, can you use DoH app on ur phone “Intra”, and open MI home app, do screenshot let me know which Mi domain cant resolve correctly

**Comment by PatPatShum** [comment]
These seem to be the ones with issues. There are many reoccurrence of **api.io.mi.com**. That's probably the main server.

![Screenshot_20190720-151622](https://user-images.githubusercontent.com/53107113/61575768-8881c100-ab02-11e9-9f37-5c21568f3269.jpg)
![Screenshot_20190720-151806](https://user-images.githubusercontent.com/53107113/61575769-891a5780-ab02-11e9-93d8-5307d3b13a6b.jpg)
![Screenshot_20190720-151741](https://user-images.githubusercontent.com/53107113/61575770-891a5780-ab02-11e9-8372-fa10d1534189.jpg)
![Screenshot_20190720-151725](https://user-images.githubusercontent.com/53107113/61575771-891a5780-ab02-11e9-9f03-02163da23564.jpg)
![Screenshot_20190720-151657](https://user-images.githubusercontent.com/53107113/61575772-891a5780-ab02-11e9-896f-b24257ca57f4.jpg)
![Screenshot_20190720-151634](https://user-images.githubusercontent.com/53107113/61575773-89b2ee00-ab02-11e9-94d3-a64ee3534455.jpg)

**Comment by ookangzheng** [comment]
Okay I whitelisted on Japan server, try again

**Comment by PatPatShum** [comment]
Wow thanks it's working great! Much appreciate your work and effort on the DNS. Many thanks!
