### ISSUE TITLE
Blahdns block sticker load in Zalo app

### ISSUE THREAD

**Issue by wh4tth3fuk** [ookangzheng/blahdns#44]
Thanks for good DNS but I have once problem.
My sticker cant load in Zalo app. Playstore link: https://play.google.com/store/apps/details?id=com.zing.zalo
Please help me fix!

![Screenshot_20190724-180854_Zalo](https://user-images.githubusercontent.com/8821381/61789306-8a1ef200-ae3e-11e9-941e-f1fc32453bc8.jpg)

**Comment by ookangzheng** [comment]
Problem solved 
Whitelisted
```
api.zaloapp.com
zaloapp.com
```
