### ISSUE TITLE
Whitelist request

### ISSUE THREAD

**Issue by wh4tth3fuk** [ookangzheng/blahdns#45]
- Pornhubpremium
- Zedge wallpaper download on Android

**Comment by ookangzheng** [comment]
-[x] pornhubpremium.com Done
-[x] Zedge wallpaper -- is working for me

**Comment by wh4tth3fuk** [comment]
> * [x]  pornhubpremium.com Done
> * [x]  Zedge wallpaper -- is working for me

Thank you. Today all my problems is solved.
