### ISSUE TITLE
Please block Xiaomi/Miui ads, spyware, calling home.

### ISSUE THREAD

**Issue by gandv** [ookangzheng/blahdns#47]
Xiaomi phone are cheap and also known for ads, spyware, tracking and calling home.  Personally I seen, Xiaomi phone with their app or services disabled or inactive still continuing to connect back to their servers in the background.  Blocking them didn't affect the phone normal functions, so whatever it is doing is not for the user.

So it will be good if you can add these entries to your blocklist, these entries were collected from other users and also my own dns logs.  Then when we use blahdns, we don't have to manually block them anymore.

`
a.stat.xiaomi.com
abtest.mistat.intl.xiaomi.com
abtest.mistat.xiaomi.com
adv.sec.miui.com
api.ad.intl.xiaomi.com
api.ad.xiaomi.com
api.admob.xiaomi.com
api.d.xiaomi.com
api.hybrid.intl.xiaomi.com
app.chat.global.xiaomi.net
authbe.sec.intl.miui.com
cc.sys.intl.xiaomi.com
cc.sys.miui.com
ccc.sys.intl.xiaomi.com
ccc.sys.miui.com
cdn.ad.xiaomi.com
connect.rom.miui.com
data.mistat.intl.xiaomi.com
data.mistat.xiaomi.com
data.sec.miui.com
e.ad.xiaomi.com
feedback.miui.com
geofence.sys.miui.com
global.market.xiaomi.com
globalapi.ad.xiaomi.com
logupdate.avlyun.sec.miui.com
mazu.sec.miui.com
metok-ccc.intl.xiaomi.com
new.api.ad.xiaomi.com
resolver.msg.global.xiaomi.net
resolver.msg.xiaomi.net
sa.api.intl.miui.com
sdkconfig.ad.intl.xiaomi.com
sdkconfig.ad.xiaomi.com
ssp.ad.xiaomi.com
test.ad.xiaomi.com
test.e.ad.xiaomi.com
test.new.api.ad.xiaomi.com
tracking.intl.miui.com
tracking.miui.com
weatherapi.market.xiaomi.com

`

**Comment by ookangzheng** [comment]
Sorry, I have some user use Xiaomi smart device if I block it, they won't be able function anymore.

**Comment by gandv** [comment]
Perhaps you can still block most of them and exclude those few domains that some user have asked for whitelisting.

**Comment by ookangzheng** [comment]
@gandv I did blocked some ads and log tracking domains 😄

**Comment by gandv** [comment]
Thank you
