### ISSUE TITLE
Having Problems with Plex

### ISSUE THREAD

**Issue by rj452** [ookangzheng/blahdns#48]
I think it's blocking Plex Servers. I keep getting this message when I'm using Blahdns. Disabling Secure Connections in Plex let's me access the server
![IMG_20190806_165236](https://user-images.githubusercontent.com/20613912/62526030-0405a100-b86b-11e9-889d-e64da1bee138.jpg)

**Comment by ookangzheng** [comment]
What is the URL? Can you do ` dig xxx.com ` and let me know the return answer

Thanks

**Comment by rj452** [comment]
I'm not sure how to do that... Is there anyway to contact you? I could give you my account.

**Comment by ookangzheng** [comment]
Email: hi#blahdns.com

**Comment by ookangzheng** [comment]
Problem solved via 
```
*.plex.direct without DNSSEC validation. 
```

**Comment by rj452** [comment]
Sorry for being a bother. But it's happen again 😭
