### ISSUE TITLE
DNS-over-TLS not working with Android Private DNS

### ISSUE THREAD

**Issue by rj452** [ookangzheng/blahdns#49]
I'm trying to use DNS-over-TLS of the 3 servers with Android's Private DNS feature and I keep getting this error on Chrome with every website.

This site can’t be reached github.com’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by zer0fl0w** [comment]
they are currently not working. same issues for me. okz is already informed. for the time being use an alternate dns or switch private dns off until okz responds.

**Comment by ookangzheng** [comment]
@rj452 @zer0fl0w Sorry for your inconvenience. 
knot-resolver server was down. I restarted abt 15minits ago, pls try again. 

Thanks

**Comment by zer0fl0w** [comment]
works for me again. thanks for your instant support. i think you can close the issue. thanks again.

**Comment by rj452** [comment]
Thank you so much! ♥️ @ookangzheng
