### ISSUE TITLE
Whitelist Request

### ISSUE THREAD

**Issue by yilmzfurkan** [ookangzheng/blahdns#50]
While "catbox.moe" is working fine the subdomain "files.catbox.moe" is blocked. 

Example: https://files.catbox.moe/yecxf3.jpg
![notblock](https://user-images.githubusercontent.com/17622232/62820667-5ba85300-bb70-11e9-9f77-a389f259b8fa.png)
![blocked](https://user-images.githubusercontent.com/17622232/62820670-5e0aad00-bb70-11e9-8b07-1d99be22a9d8.png)

**Comment by ookangzheng** [comment]
Done
