### ISSUE TITLE
New advertising on smartphone because of facebook

### ISSUE THREAD

**Issue by Dadan59DK** [ookangzheng/blahdns#52]
Hello,

I've come to point out a new trackers, it's facebook that now puts ads on applications. When I click on the ad to get information, I get the following message:

"The app or website you visited uses Facebook Audience Network to show you the most relevant ads.

Improve the ads you see by managing your advertising preferences or giving your opinion on this ad."

Screenshot: https://www.casimages.com/a/ZU0Be

Can you find a solution for smartphones.

Adchoices could not be blocked by blah dns.... Can it be refiltered?

Screenshot: https://www.casimages.com/a/U7Sm7

https://www.casimages.com/i/190817030036151113.jpg.html

Thank you.

**Comment by ookangzheng** [comment]
Pls don't use blockada, use Nebulo or personalDNS instead.
I can't reproduce ur problem but give me some time to figure it out.
