### ISSUE TITLE
Doesn't work in Adguard for android.

### ISSUE THREAD

**Issue by Techguyprivate** [ookangzheng/blahdns#53]
Blahdns is not working in adguard for android. I have tried everything dot, doh  & dnscrypt too. Nothinh works. I have tried different ports mentioned too. 

Steps to reproduce.

1. Install adguard for android from adguard websites, not available in playstore.
2. Go to setting, then dns . 
3. Write the balhdns address.
4. Showing no connection.
![Screenshot_2019-08-24-22-14-37-09_a93965f46c4a4b0ed1be737bdf2bc8fc](https://user-images.githubusercontent.com/43615747/63641015-e623a300-c696-11e9-91a3-ea1e4176c8d5.png)
 Any help, guidance are really appreciated. Thank you in advance.

**Comment by zer0fl0w** [comment]
you say that you use android 9. so you could use the inbuild native private dns function of android for setting dns. no need for adguard. 

otherwise try entering the url into adguard without http:// or https:// or tls:// ... only enter the domain itself like: dot-jp.blahdns.com

im not sure about adguard, but okz recommends other clients, check readme -> https://github.com/ookangzheng/blahdns/blob/master/README.md

**Comment by Techguyprivate** [comment]
![Screenshot_2019-08-25-01-15-51-42_a93965f46c4a4b0ed1be737bdf2bc8fc](https://user-images.githubusercontent.com/43615747/63642056-79c89400-c6d6-11e9-9a97-fc83a4724129.png)
 Still don't work. Blahdns works with almost all other dns apps.

**Comment by zer0fl0w** [comment]
does adguard can handle domainnames as dns? looks like it expects you enter ip for dns, like i.e. 8.8.8.8.

**Comment by Techguyprivate** [comment]
![Screenshot_2019-08-25-11-46-25-17_a93965f46c4a4b0ed1be737bdf2bc8fc](https://user-images.githubusercontent.com/43615747/63646339-97125800-c700-11e9-9b74-2960aacc8ab9.png)

**Comment by ookangzheng** [comment]
> Blahdns is not working in adguard for android. I have tried everything dot, doh & dnscrypt too. Nothinh works. I have tried different ports mentioned too.
> 
> Steps to reproduce.
> 
> 1. Install adguard for android from adguard websites, not available in playstore.
> 2. Go to setting, then dns .
> 3. Write the balhdns address.
> 4. Showing no connection.
>    ![Screenshot_2019-08-24-22-14-37-09_a93965f46c4a4b0ed1be737bdf2bc8fc](https://user-images.githubusercontent.com/43615747/63641015-e623a300-c696-11e9-91a3-ea1e4176c8d5.png)
>    Any help, guidance are really appreciated. Thank you in advance.

I don't know what is going wrong with blahdns + adguard android. I'm still busy with my studies. Please use Nebulo or https://zenz-solutions.de/personaldnsfilter/ instead.

**Comment by ookangzheng** [comment]
#60
