### ISSUE TITLE
Unable to check Blahdns status from mobile

### ISSUE THREAD

**Issue by Techguyprivate** [ookangzheng/blahdns#54]
I am unable to check blahdns status from mobile from chrome for android. It is simply not loading, showing three animated dots. 

stats.blahdns.com

**Comment by zer0fl0w** [comment]
it seems to be a problem with uptimerobot because other sites also show no status currently. it most likely not blahdns related.

**Comment by zer0fl0w** [comment]
i just checked again. uptimerobot is experiencing some performance-impacts which results in very slow services.

you have to wait like a minute on the 3-dot screen until the status gets shown.

**Comment by Techguyprivate** [comment]
Yes, confirmed. Have to wait for 3 minutes from here. Rather odd. I think that it is little bit too much to load. Can't it be made fast?

**Comment by zer0fl0w** [comment]
normally it is much faster, but uptimerobot is an external service not related to blahdns. so there is absolutely no influence from blahdns to performance-improvements on their end. nevertheless its just a temporary issue and will be back to normal relatively soon.

**Comment by ookangzheng** [comment]
> Yes, confirmed. Have to wait for 3 minutes from here. Rather odd. I think that it is little bit too much to load. Can't it be made fast?

As @zer0fl0w said, uptimerobot is third-party service platform to monitor blahdns services. In the future, I will code a similar service as well. Therefore don't need to rely on uptimerobot.

Thanks.
