### ISSUE TITLE
I have a request

### ISSUE THREAD

**Issue by cloudyytechie** [ookangzheng/blahdns#6]
Hey could you please keep port 53 open because I can’t use dns crypt on my router because it doesn’t support it I’m a bit stuck because if port 53 is closed I can’t use the dns

**Comment by ookangzheng** [comment]
I'm sorry I think I couldn't make it because I need to decrease some random DNS attack on port 53.
When some attack coming, I need to buy a lot of traffic to buffer attack, cost a lot 😢

**Comment by cloudyytechie** [comment]
It’s okay if you have to close port 53

**Comment by ookangzheng** [comment]
@cloudyytechie  Are you using Germany server? If so I can keep port 53 open.
