### ISSUE TITLE
Can not resolve ipv4only.arpa with BlahDNS DoT servers

### ISSUE THREAD

**Issue by admitrevskiy** [ookangzheng/blahdns#60]
Hi!

There are no answer records for `ipv4only.arpa` DNS question on Blah DNS JP and DE DoT servers.
However, CH DoT server contains valid records.

Could you add answer records for `ipv4only.arpa` for all your servers?

**Comment by ookangzheng** [comment]
What does `ipv4only.arpa` for? I blacklisted it before, but now whitelisted

**Comment by admitrevskiy** [comment]
`ipv4only.arpa` is reserved domain name for "Well-known ipv4" addresses. A request should be answered with 192.0.0.170 and 192.0.0.171; AAAA request should be answered with Pref64::192.0.0.[170|171] if your server supports DNS64

In short it is necessary for client to discover if your server supports DNS64.

**Comment by ookangzheng** [comment]
@admitrevskiy I see but my server which has Knot-resolver, Unbound doenst resolve `ipv4only.arpa ` type `aaaa`
It returns this answer
```
dig ipv4only.arpa aaaa @::1 -p 55

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> ipv4only.arpa aaaa @::1 -p 55
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64145
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ipv4only.arpa.			IN	AAAA

;; AUTHORITY SECTION:
ipv4only.arpa.		7	IN	SOA	sns.dns.icann.org. noc.dns.icann.org. 2019082706 7200 3600 604800 3600

```

**Comment by ameshkov** [comment]
@ookangzheng that's okay, this is how it should be with a public DNS resolver like yours.

Only DNS64 servers can answer an `AAAA` query for this domain, and this usually happens in iPv6-only networks configured with [NAT64/DNS64](https://tools.ietf.org/html/rfc6147).
