### ISSUE TITLE
Whitelist Request

### ISSUE THREAD

**Issue by rj452** [ookangzheng/blahdns#65]
Can you please unblock Tapas? 
api.tapas.io/0.0.0.0:443
Thank you!
![Screenshot_2019-09-29-22-38-33-915_com tapastic](https://user-images.githubusercontent.com/20613912/65834120-506cda80-e30a-11e9-988a-2105ea2b73cd.png)

**Comment by ookangzheng** [comment]
Done

**Comment by rj452** [comment]
Thank you! 😁
