### ISSUE TITLE
add support yggdrasil network

### ISSUE THREAD

**Issue by KonoromiHimaries** [ookangzheng/blahdns#66]
https://yggdrasil-network.github.io/about.html

**Comment by Mikaela** [comment]
Being able to access BlahDNS through Yggdrasil would be nice, I assume that is what you mean?

Otherwise I think BlahDNS is already capable of resolving names such as `y.relpda.mikaela.info`.

**Comment by ookangzheng** [comment]
> y.relpda.mikaela.info

What is this for ?

**Comment by ookangzheng** [comment]
I installed yggdrasil on both machines, should I announce it to public node?

**Comment by Mikaela** [comment]
>> y.relpda.mikaela.info
> 
> What is this for ?

It's a domain that only has AAAA record pointing to Yggdrasil address so it cannot be ping6ed or anything unless your host has Yggdrasil compatibility.

> I installed yggdrasil on both machines
> __Test and feedback needed__

Nice, thanks, I think I will be able to try the day after tomorrow, but I cannot give promises.

**Comment by ookangzheng** [comment]
In my VPS which connected to Yggdrasil and I can do DoT over kdig to both Blahdns

**Comment by ookangzheng** [comment]
I also implemented `.eth` TLD, welcome give it a try
`dig almonit.eth`

**Comment by Mikaela** [comment]
Seems to work with this Unbound config :+1: 

```
    forward-addr: 201:742c:871d:24ef:c850:e1ff:41c7:12bc@443#dot-de.blahdns.com
    forward-addr: 201:4a30:a6f7:e766:84bb:f6b4:bcd8:3483@443#dot-ch.blahdns.com
    forward-addr: 202:f97c:46c8:d7b4:71f1:7e8b:2e64:353d@443#dot-jp.blahdns.com
```

I see log entries such as

```
Oct 08 20:42:09 sedric unbound[7173]: [7173:1] info: reply from <.> 201:4a30:a6f7:e766:84bb:f6b4:bcd8:3483#443
Oct 08 20:42:10 sedric unbound[7173]: [7173:1] info: reply from <.> 201:742c:871d:24ef:c850:e1ff:41c7:12bc#443
Oct 08 20:42:11 sedric unbound[7173]: [7173:1] info: reply from <.> 201:742c:871d:24ef:c850:e1ff:41c7:12bc#443
Oct 08 20:42:10 sedric unbound[7173]: [7173:1] info: reply from <.> 202:f97c:46c8:d7b4:71f1:7e8b:2e64:353d#443
```

I have a long resolver list and I am relying on Unbound to pick the best ones. BlahDNS is the only filtering one I have enabled though as port 443 is so rare and I am not entirely sure on filtering UTF-8 domain names as I have a friend with one.

**Comment by ookangzheng** [comment]
> Seems to work with this Unbound config 👍
> 
> ```
>     forward-addr: 201:742c:871d:24ef:c850:e1ff:41c7:12bc@443#dot-de.blahdns.com
>     forward-addr: 201:4a30:a6f7:e766:84bb:f6b4:bcd8:3483@443#dot-ch.blahdns.com
>     forward-addr: 202:f97c:46c8:d7b4:71f1:7e8b:2e64:353d@443#dot-jp.blahdns.com
> ```
> 
> I see log entries such as
> 
> ```
> Oct 08 20:42:09 sedric unbound[7173]: [7173:1] info: reply from <.> 201:4a30:a6f7:e766:84bb:f6b4:bcd8:3483#443
> Oct 08 20:42:10 sedric unbound[7173]: [7173:1] info: reply from <.> 201:742c:871d:24ef:c850:e1ff:41c7:12bc#443
> Oct 08 20:42:11 sedric unbound[7173]: [7173:1] info: reply from <.> 201:742c:871d:24ef:c850:e1ff:41c7:12bc#443
> Oct 08 20:42:10 sedric unbound[7173]: [7173:1] info: reply from <.> 202:f97c:46c8:d7b4:71f1:7e8b:2e64:353d#443
> ```
> 
> I have a long resolver list and I am relying on Unbound to pick the best ones. BlahDNS is the only filtering one I have enabled though as port 443 is so rare and I am not entirely sure on filtering UTF-8 domain names as I have a friend with one.
> 
> EDIT: if anyone is curious, I see these in extended dnsleak.com test right now:
> 
> ![kuva](https://user-images.githubusercontent.com/831184/66420568-c65df980-ea0e-11e9-89eb-4edc5bcd7bfe.png)

You can use Port 853 as well for DoT... 
What do you mean `BlahDNS is the only filtering one I have enabled though as port 443 is so rare and I am not entirely sure on filtering UTF-8 domain names as I have a friend with one.`
filtering UTF-8 domain?

**Comment by Mikaela** [comment]
> You can use Port 853 as well for DoT...

I prefer to appear in statistics as using the port 443.

> BlahDNS is the only filtering one I have enabled though as port 443 is so rare

I have multiple DNS servers configured in my Unbound, but most of them are only in port 853, so I fear that I wouldn't have connectivity issues to them with heavily firewalled networks.

* https://gitea.blesmrt.net/mikaela/shell-things/src/branch/master/etc/unbound/unbound.conf.d/dns-over-tls.conf

> filtering UTF-8 domain?

I meant how non-ASCII wasn't allowed, but you seem to have changed that policy judging by https://github.com/ookangzheng/blahdns/commit/85ba2e0d95d38ea60100e1344ddb275a937b411c, thank you :purple_heart:

**Comment by ookangzheng** [comment]
@Mikaela Can you remove this?
<img width="1126" alt="Screen Shot 2019-10-11 at 11 31 06" src="https://user-images.githubusercontent.com/6301735/66621017-92a4ee80-ec1d-11e9-8492-247df9d59a86.png">

**Comment by Mikaela** [comment]
Sorry, I forgot. https://github.com/privacytoolsIO/privacytools.io/pull/1396

**Comment by ookangzheng** [comment]
No further discussion here? I gonna close this issue 😄
