### ISSUE TITLE
Cerificate about to expire

### ISSUE THREAD

**Issue by QuantumLeap-BEL** [ookangzheng/blahdns#67]
from dnscrypt-proxy log:
[2019-10-02 16:39:15] [CRITICAL] [2.dnscrypt-cert.blahdns.com.] certificate will expire today -- Switch to a different resolver as soon as possible

**Comment by ookangzheng** [comment]
Hmm Interesting...  I will fix it

**Comment by ookangzheng** [comment]
Fixed... Enjoy

**Comment by QuantumLeap-BEL** [comment]
Thank you. I've filled in a suggestion form on your site a few days ago, but that one went into the void I guess 🤨
Gives another error now:
 [2.dnscrypt-cert.blahdns.com.] Incorrect signature

**Comment by ookangzheng** [comment]
The signature has been fixed. Cuz you have to wait for dnscrypt-resolver repo to accept my signature :D

**Comment by ookangzheng** [comment]
@QuantumLeap-BEL still having this issue?

**Comment by QuantumLeap-BEL** [comment]
Yes and dnscrypr-proxy doesn't use the server due to this issue.
[2019-10-03 16:34:02] [WARNING] [2.dnscrypt-cert.blahdns.com.] Incorrect signature

**Comment by ookangzheng** [comment]
Can you share your dnscrypt-proxy.toml here?

**Comment by QuantumLeap-BEL** [comment]
I was in bootcamp and just back in macOS. It works now. Cheers!

**Comment by kowith337** [comment]
Noticed it seems like expired again.

My timezone is GMT+7, so the deadline time passed...

![image](https://user-images.githubusercontent.com/16535467/67945406-632c4500-fc11-11e9-909d-48c49025924c.png)
