### ISSUE TITLE
Google AMP

### ISSUE THREAD

**Issue by rj452** [ookangzheng/blahdns#68]
Google Accelerated Mobile Page (AMP) is not working.
E.g. https://www.google.com/amp/s/www.cnet.com/google-amp/news/google-reportedly-attains-quantum-supremacy/
![Screenshot_2019-10-07-11-19-19-217_com android chrome](https://user-images.githubusercontent.com/20613912/66283023-58251400-e8f4-11e9-8d9a-ed2734af2271.png)

**Comment by ookangzheng** [comment]
now i can open it. try again
Screenshot https://prnt.sc/pg1n9d

**Comment by rj452** [comment]
@ookangzheng working now. Thank you! 😊

**Comment by Bec-de-Xorbin** [comment]
AMP sites do work but it takes 5-10 seconds before anything comes to screen.

**Comment by rj452** [comment]
@ookangzheng AMP is not working again.

**Comment by ookangzheng** [comment]
@rj452 Fixed.. sorry
