### ISSUE TITLE
¿Add unsecure dns?

### ISSUE THREAD

**Issue by wuniversales** [ookangzheng/blahdns#70]
Hello, I wish you could also connect in a non-secure way to dns, for special devices, consoles (Video games), etc ...
I would like to configure the router with these dns, thanks, Regards
Thanks greetings

**Comment by ookangzheng** [comment]
Sorry, It cost too much to maintain it. 
I'd suggest you give this a try 
https://public-pihole.com/

**Comment by ookangzheng** [comment]
@wuniversales Problem solved?
