### ISSUE TITLE
NHL app doesn't play videos

### ISSUE THREAD

**Issue by Bec-de-Xorbin** [ookangzheng/blahdns#71]
[NHL app](https://play.google.com/store/apps/details?id=com.nhl.gc1112.free) in Android doesn't play highlight etc. videos in app. Using dns.adguard.com videos work and without ads also. I used Intra to check DNS queries and I think the culprit is **imasdk.googleapis.com** which is blocked (but not blocked when using Adguard DNS). I can see that imasdk.googleapis.com is included in whitelist.txt but why is it still blocked?

**Comment by ookangzheng** [comment]
Problem solved.

**Comment by Bec-de-Xorbin** [comment]
Indeed. Thank you!
