### ISSUE TITLE
is there any reason for Swiss server shutdown?

### ISSUE THREAD

**Issue by GETandSELECT** [ookangzheng/blahdns#73]
Hi

thank you for great service.

is there any reason for Swiss server shutdown? Is there something what you didn't like in this location?

**Comment by ookangzheng** [comment]
Expensive 😅

**Comment by ookangzheng** [comment]
Do you have any VPS provider that affordable for me?

**Comment by Mikaela** [comment]
I don't know if it helps here, but I have a VPS at https://i-83.net/ which I find affordable, however they are IPv6-only (or 20 weird IPv4 ports) so probably not very helpful for hosting DNS (unless everyone uses Unbound or something else that allows using artificial port instead of 853 or 443).
