### ISSUE TITLE
Website blocked or acsess failed.

### ISSUE THREAD

**Issue by master4x** [ookangzheng/blahdns#78]
Hi,
I use your DNS-Service for about a week and really likei t!
For now i am connected to dot-de.* and it works mostly fine,
the only website that seems to be blocked is: shoppy.gg
That's a website where you can buy any type of digital goods from privats.
I looked it up in yout blacklist, but found no entry,
can you add shoppy to the whitelist pls?

Kepp the project going!

master4x

**Comment by ookangzheng** [comment]
Fixed
