### ISSUE TITLE
Add porn filter

### ISSUE THREAD

**Issue by wuniversales** [ookangzheng/blahdns#79]
It would be nice to have a pornographic filter to not be able to access that kind of content.

**Comment by ookangzheng** [comment]
You can check it out this https://github.com/bhanupratapys/dnswarden
It supported all major DNS encryption protocol, also has Porn filter functionality.

**Comment by ookangzheng** [comment]
There are some alternative to filter porn
1. Cloudflare Family -> 1.0.0.3, 1.1.1.3
2.Adguard Family -> 176.103.130.132, 176.103.130.134
3. Cleanbrowsing Family -> 185.228.168.10, 185.228.169.10
