### ISSUE TITLE
The Links on the IP Address Information page don’t work

### ISSUE THREAD

**Issue by aschimmichanga** [ookangzheng/blahdns#82]

**Comment by ookangzheng** [comment]
what link?

**Comment by aschimmichanga** [comment]
https://doh-fi.blahdns.com/dns-query
https://doh-de.blahdns.com/dns-query
https://doh-jp.blahdns.com/dns-query

Ashna Srivastava

**Comment by ookangzheng** [comment]
This is for DNS-over-HTTPS.. not a webpage... 
Is the entry point for DoH
