### ISSUE TITLE
Whitelist request

### ISSUE THREAD

**Issue by ukwiddy** [ookangzheng/blahdns#84]
Please can you allow the UK National Lottery site. www.national-lottery.co.uk

Many thanks

**Comment by ookangzheng** [comment]
Try it again

**Comment by ukwiddy** [comment]
Still unable to access either the site directly or through their own app. 

Disabling blahdns and it then loads.

**Comment by ookangzheng** [comment]
I already whitelist their URL `www.national-lottery.co.uk` and I can visit on my laptop

**Comment by ukwiddy** [comment]
![Screenshot_20200116-150541](https://user-images.githubusercontent.com/59807775/72536231-c6715f00-3871-11ea-8c28-edef9f62d93a.jpg)


I'm still unable to view the site. I've even tried rebooting my device.

**Comment by ookangzheng** [comment]
If you still having this issue, pls reopen this ticket.
Thanks
