### ISSUE TITLE
Whitelist Microsoft "Your Phone"

### ISSUE THREAD

**Issue by RamiEjailat** [ookangzheng/blahdns#85]
When blahdns is active on my Android, the "Your Phone" Windows app cannot connect to the "Your Phone" Android app. If a non-blocking DNS is used, the connection is established without issues.

The domain seems to be "continuum.dds.microsoft.com" according to these reddits:
https://www.reddit.com/r/pihole/comments/drylpk/pihole_and_your_phone_companion_app_microsoft/
https://www.reddit.com/r/pihole/comments/bppug1/introducing_the/epxo5yi/?context=3

**Comment by ookangzheng** [comment]
Fixed, Thanks
