### ISSUE TITLE
Whitelist for CDN-Network

### ISSUE THREAD

**Issue by master4x** [ookangzheng/blahdns#87]
In the project, the CDN service wtcdn is blocked. On some sites it's impossible to view images. I am not sure if it is used for ads, too - but I don't think so!
Web adress for sources (such as images/scripts):
https://scr.wfcdn.de/ [...]
https://wtcdn.de

It's a German network, pls whitelist.
Thx

**Comment by ookangzheng** [comment]
Thanks and fixed
