### ISSUE TITLE
Mime type mismatch on static files

### ISSUE THREAD

**Issue by joaopgrassi** [ookangzheng/blahdns#88]
Hey, thanks for this project! 

I was browsing the website the other day using Firefox and the website is completely broken. I noticed that here's a bunch of these errors in the console:

```
The resource from “https://cdn.blahdns.com/w3.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```
Maybe you can try to "hack" it by removing the `rel` from the `<link` tag:
```
<link type="text/css" href="https://cdn.blahdns.com/w3.css">
```

It might be the webserver messing with the content types, not sure. But it should be an easy fix either way.

**Comment by ookangzheng** [comment]
Done, thanks for your report

**Comment by joaopgrassi** [comment]
Seems to be working now. I guess this can be closed then. :)
