### ISSUE TITLE
problem with session messaging app

### ISSUE THREAD

**Issue by boistordu** [ookangzheng/blahdns#90]
Hi,

It seems, but I may be wrong, that your dns is blocking the session messaging app.:
https://github.com/loki-project/session-desktop
at least on iOS. 
I think that it blocks the the session to get the ip of their tracker/ seed node. 
I don't have the IP yet because I was just testing one dns at the time.
But I'm 100% that your dns node true dnscloak is blocking the app to be able to send and receive messages.
I will get the ip asap but in the mean time could you look into it?

**Comment by boistordu** [comment]
for reference the github problem on session 
https://github.com/loki-project/session-desktop/issues/1063

**Comment by boistordu** [comment]
i might be imaginary.stream but not sure. I don't have confirmation yet but that's what I can see from glasswire and pihole.

**Comment by boistordu** [comment]
"seedNodeList": [
    {
      "ip": "public.loki.foundation",
      "port": "22023"
    },
    {
      "ip": "storage.seed1.loki.network",
      "port": "22023"
    },
    {
      "ip": "storage.seed2.loki.network",
      "port": "38157"
    },
    {
      "ip": "imaginary.stream",
      "port": "38157"
    }
  ],

**Comment by ookangzheng** [comment]
> imaginary.stream

I tested both url not being blocked.

**Comment by boistordu** [comment]
@ookangzheng dit might be something else but did you try with using dnscloak on iOS for example and the session app? 
I'm proposing this test bench because it is the most simple one. It won't interact with antivirus, firewall or whatever....
Don't forget it might be a timeout problem too. The response being too slow to arrive will not be taken into account.
