### ISSUE TITLE
Finland DOT and DOH is down

### ISSUE THREAD

**Issue by shumvgolove** [ookangzheng/blahdns#92]
Starting from today, the Finland DNS has stopped working. Pinging `dot-fi.blahdns.com` works, but DNS doesn't resolve anything.

Japan and German DNS work fine.

**Comment by AXKuhta** [comment]
Looks like the certificate has expired, if you try open `https://doh-fi.blahdns.com/dns-query` in browser.

**Comment by shumvgolove** [comment]
Yeah, #36 mentions that Finland cert expiring at April 21, 2020.

**Comment by ookangzheng** [comment]
Fixed. Thanks for your report

**Comment by shumvgolove** [comment]
Сan confirm, thank you!
