### ISSUE TITLE
Japan server not compatible with anonymized dns

### ISSUE THREAD

**Issue by black-ish** [ookangzheng/blahdns#94]
Hello,
I tried various relays and everytime I use one with the "dnscrypt-jp-blahdns-ipv4" server I either get told that it's not compatible or if it doesn't tell me that then I can only get NETWORK_ERROR.

Could that be checked into?

**Comment by ookangzheng** [comment]
This sound interesting though I'm little bit busy these day, give me some time to check it out.

**Comment by black-ish** [comment]
Thank you, it seems to work now, what was done if I may ask?

**Comment by ookangzheng** [comment]
I switched to master branch of dnsdist, and reinstall. 
Thats it.

**Comment by black-ish** [comment]
Well that fixed it it seems, thank you :+1: 
I guess this can be closed now.
