### ISSUE TITLE
blocks Huawei icons

### ISSUE THREAD

**Issue by Jostian** [ookangzheng/blahdns#97]
First off thanks for a great dns, it works brilliant! But on my Huawei phone (Mate 20 pro), it blocks all the app icons (pictures) in the Huawei app store, and Huawei Themes app, so I cannot see any of the icons or pictures or wallpapers in the 2 apps, any way to get around this? If I turn off the DNS they both work perfect, hope you can help. Thanks

**Comment by ookangzheng** [comment]
Could you do me a favor?
Pls install Infra (DNS-over-HTTPS)  and send me screenshot of the Huawei address that miss blocked on your phone. Then I can whitelist it. 

Thanks

**Comment by Jostian** [comment]
Thanks, not sure where to find Infra? Is it a apk that i install on phone,
kindly J

**Comment by ookangzheng** [comment]
Sorry, the app called Intra, Link: https://play.google.com/store/apps/details?id=app.intra

**Comment by Jostian** [comment]
Thanks

**Comment by Jostian** [comment]
I installed it but this is all i see, no idea how to see the necessary info
for the 2 Huawei apps?

**Comment by ookangzheng** [comment]
1. Open, Intra app
2. Type in `https://doh-jp.blahdns.com/dns-query` as custom DoH server
3. Start the Intra service
4. Under Log area, you can see what domain has been blocked.
5. Open Huawei app 
6. Return to Intra app, and do a screenshot ( where you can see Huawei related recent connection)

**Comment by Jostian** [comment]
Thanks, will do

**Comment by Jostian** [comment]
Hi here are the 2 screenshots for when i try open Huawei appstore and
Huawei themes app, both get images and icons blocked, hope these help, many
thanks.

**Comment by ookangzheng** [comment]
Where is the screenshots? Are you forget to attach on GitHub or send it via email: hi@blahdns.com

**Comment by Jostian** [comment]
Hi, they are attached in my previous email

**Comment by ookangzheng** [comment]
@Jostian  Could you pls try it again

**Comment by Jostian** [comment]
Hey all working fine, awesome, thanks!
